### ISSUE TITLE
Support for stateless JWT access tokens

### ISSUE THREAD

**Issue by ccbrown** [ory/fosite#140]
I've been trying to figure out how to use JWT access tokens statelessly, but all of the examples are actually persisting them to storage as far as I can tell. I have something that works, but I feel like this is a bit too messy and should be made easier by fosite.

Currently, I'm doing this:

* Issuing the access tokens as usual, but my `CreateAccessTokenSession` method is a no-op:

    ```go
    func (s *OAuth2Storage) CreateAccessTokenSession(ctx context.Context, signature string, request fosite.Requester) (err error) {
        return nil
    }
    ```

* In my request handling, decoding the token to the `JWTSession`:

    ```go
    token, err := strategy.Decode(response.GetAccessToken())
    assert.NoError(t, err)
    claims := token.Claims.(jwtgo.MapClaims)
    session = &oauth2.JWTSession{
        Subject: claims["sub"].(string),
    }
    ```

* In my `GetAccessTokenSession` method, building a requester with the decoded session:

    ```go
    func (s *OAuth2Storage) GetAccessTokenSession(ctx context.Context, signature string, session fosite.Session) (request fosite.Requester, err error) {
        return &fosite.Request{Session: session}, nil
    }
    ```

* Passing the decoded session to `IntrospectToken` for validation:

    ```go
    ar, err := provider.IntrospectToken(ctx, response.GetAccessToken(), fosite.AccessToken, session, "")
    assert.NoError(t, err)
    assert.Equal(t, ar.GetSession().GetSubject(), "123")
    ```

Is there a better way to do this? It seems like a pretty common need. After all, that's a very large part of the appeal of using JWT for access tokens.

Hopefully I'm just missing something silly here.

**Comment by arekkas** [comment]
The idea of persisting the JWT in the store is that one is able to revoke access and refresh tokens, and also to make it harder to forge tokens, as one requires access to the database.

**Comment by ccbrown** [comment]
Revocation with stateless JWTs is done with blacklists. The advantage being lower storage requirements, and the drawback being round-trips to a centralized database of revocations. A lot of people use JWTs to avoid hitting a database, and opt for short-lived tokens with small expiration times over instantaneous revocation though. That's what I want in this case.

Refresh tokens simply don't require the _access token_ to be stored. The refresh token, on the other hand, _is_ stored, along with the scope, subject, etc. I don't think refreshing is at all a factor in this issue. I'm only interested in stateless _access tokens_.

Forging tokens seems like a bit of a non-concern either way, as one requires access to the private signing key, which can be stored in the database as well (and often is since using different keys for each client is pretty common).

**Comment by arekkas** [comment]
> A lot of people use JWTs to avoid hitting a database

This is partially true, JWTs have the benefit that the client side does not need to hit the authorization server in order to validate the token. However, if you want your system to support token revokation, you will either need to publish the black list to all resource providers or you will need to ask the authorization server if the token is still valid. That is the key benefit and tradeoff when it comes to JWTs.

If you're working on a monolithic application, the same rules apply. You might want to implement some sort of interface `interface AuthorizationService { IsAuthorized(token) }` that uses only the priv/pub keypairs for validating and skips asking the database for any information whatsoever. Here, you are also free to introduce a black list as you proposed, sidestepping some parts of the fosite logic. Or, as you proposed, writing a noop storage interface

**Comment by ccbrown** [comment]
Would you be open to a pull request for a few additions that would make this sort of thing easier?

Specifically, I'm thinking a method to deserialize a JWT into `JWTClaims` (the opposite of `ToMap`) and a `TokenIntrospector` implementation that constructs an access request directly from the JWT (after validating it of course).

**Comment by arekkas** [comment]
Sure, maybe you could scaffold a quick draft so I better understand what you want to do :)

**Comment by ccbrown** [comment]
Of course.

My end goal is simply for the majority of my requests to not require storage lookups. For my use case, revocation isn't a requirement at all.

So I think I would propose a `JWTValidator` struct that implements `TokenIntrospector` and can be used to validate access tokens.

It would behave something like this:

```go
type JWTAccessTokenStrategy interface {
    AccessTokenStrategy
    jwt.JWTStrategy
}

type JWTValidator struct {
    JWTAccessTokenStrategy
}

func (v *JWTValidator) IntrospectToken(ctx context.Context, token string, tokenType fosite.TokenType, accessRequest fosite.AccessRequester, scopes []string) (err error) {
    if tokenType != fosite.AccessToken || len(scopes) > 0 {
        return fosite.ErrUnknownRequest
    }

    decoded, err := v.Decode(token)
	if err != nil {
		return errors.Wrap(fosite.ErrRequestUnauthorized, err.Error())
    }

    claims := jwt.JWTClaims{}
    claims.FromMapClaims(decoded.Claims.(jwtgo.MapClaims)) // new method: opposite of ToMapClaims

    or := &fosite.Request{
		Client: &fosite.DefaultClient{
            ID: claims.Audience,
		},
		Session: &JWTSession{
			JWTClaims: &claims,
			JWTHeader: &jwt.Headers{
				Extra: make(map[string]interface{}),
			},
			ExpiresAt: map[fosite.TokenType]time.Time{
				tokenType: claims.ExpiresAt,
			},
            Subject: claims.Subject,
		},
	}

	if err := v.JWTAccessTokenStrategy.ValidateAccessToken(ctx, or, token); err != nil {
		return err
	}

	accessRequest.Merge(or)
	return nil
}
```

And with that registered in `TokenIntrospectionHandlers`, you don't actually need a storage implementation at all to verify JWT access tokens. You can verify the validity and get the subject via the norm:

```go
f.IntrospectToken(ctx, fosite.AccessTokenFromRequest(req), fosite.AccessToken, mySessionData, requiredScope)
```

The only limitations I'm aware of (aside from revocation caveats) are it can only be used for access tokens, and you can't specify any required scopes (Specifying required scopes should be perfectly valid, but would take a little more work since I don't think fosite actually writes them to the JWTs at the moment.).

I've actually gone ahead and implemented this with a few tests just to sanity check myself and make sure this actually meets the needs of this use-case:

[stateless-jwt-diff.txt](https://github.com/ory-am/fosite/files/719483/stateless-jwt-diff.txt)
