### ISSUE TITLE
Allow http for subdomains of localhost

### ISSUE THREAD

**Issue by matteosuppo** [ory/fosite#146]
Some fellow developers complained that they use to host their development instances on urls like

http://moodle.localhost

But fosite don't allow such subdomains to run on http: https://github.com/ory/fosite/blob/c740b703399e7a1479dac9f261baec4b341f6cff/authorize_helper.go#L103

Is there a reason why it shouldn't, or is it simply an oversight? If it's the latter I can provide a pull request to fix it. If it's the former, no problem.

**Comment by arekkas** [comment]
Yeah, that makes sense!
