### ISSUE TITLE
Authorization code flow (Authorize Explicit Grant) doesn't issue refresh tokens

### ISSUE THREAD

**Issue by petejkim** [ory/fosite#149]
The following change in `handler/oauth2/flow_authorize_code_token.go` appears to make it work. Am I doing something wrong or is it a bug?

![screen shot 2017-03-13 at 4 23 08 pm](https://cloud.githubusercontent.com/assets/30173/23879297/6222fa2c-0809-11e7-945a-93b999c115ba.png)

**Comment by arekkas** [comment]
This does not look right. You shouldnt simply grant scopes that are requested!

Von meinem iPhone gesendet

**Comment by petejkim** [comment]
I am trying to make the `fosite-example` work. It doesn't seem to work out of the box.

**Comment by arekkas** [comment]
What are you trying to do exactly? Here everything works fine. Take note that the library is in use in production systems for over a year now, so it is unlikely that such an issue would be around.

However, I spotted an issue with the fosite-example which causes that all scopes are being granted when performing the authorize code flow, thus ignoring the input from the user during the consent screen. The lines causing this issue are [here](https://github.com/ory/fosite-example/blob/master/authorizationserver/oauth2_token.go#L29-L32). This is *not* related to the issue you described however. After performing the authorize code flow, this is the response I get from the introspection endpoint:

```
{"active":true,"client_id":"my-client","scope":"photos openid offline","exp":1489514042,"iat":1489510442} 
```

So, as you can see, the scopes are populated and contain all the requested scopes.

**Comment by petejkim** [comment]
I removed my local changes and it does appear to work.

The change I made was to use JWT Strategy and modifying the `newSession` function to return `*foauth2.JWTSession`:


```go
func newSession(user string) fosite.Session {
	now := time.Now()
	expiresAt := now.Add(time.Hour * 6)
	return &foauth2.JWTSession{
		JWTClaims: &jwt.JWTClaims{
			Issuer:    "https://fosite.my-application.com",
			Subject:   user,
			Audience:  "https://my-client.my-application.com",
			ExpiresAt: expiresAt,
			IssuedAt:  now,
			NotBefore: now.Add(-30 * time.Minute),
			Extra: map[string]interface{}{
				"test": "testing",
			},
		},
		Username: user,
		Subject:  user,
		ExpiresAt: map[fosite.TokenType]time.Time{
			fosite.AccessToken:   expiresAt,
			fosite.RefreshToken:  now.Add(time.Hour * 24 * 7),
			fosite.IDToken:       expiresAt,
			fosite.AuthorizeCode: now.Add(time.Minute * 5),
		},
	}
}
```

**Comment by petejkim** [comment]
Sorry for the trouble, yes it works as intended. The issue was not ticking the checkboxes... I was confused because even if I don't click on the checkboxes, I was still receiving all three scopes in `accessRequest.GetRequestedScopes()`

**Comment by arekkas** [comment]
Tracked as https://github.com/ory/fosite-example/issues/2 :)
