### ISSUE TITLE
exp (ExpiresAt) not set with JWT strategy and Resource Owner Password Credentials grant

### ISSUE THREAD

**Issue by wezzle** [ory/fosite#152]
I'm using the JWT strategy (compose.NewOAuth2JWTStrategy) in combination with the Resource Owner Password Credentials grant (compose.OAuth2ResourceOwnerPasswordCredentialsFactory) and i've noticed that the exp value is not correctly set on the JWT token.

When using the Client Credentials grant the exp value is correctly set. In the ClientCredentialsGrantHandler's `HandleTokenEndpointRequest` there is a line setting the expires at on the session: `request.GetSession().SetExpiresAt(fosite.AccessToken, time.Now().Add(c.AccessTokenLifespan))`. This is not done in the ResourceOwnerPasswordCredentialsGrantHandler, however adding it there will set the correct exp value on the JWT token.

Should the ResourceOwnerPasswordCredentialsGrantHandler set the expires at on the session as well or is there a reason it's not done there? Isn't this something that should be done on every handler generating tokens?

**Comment by arekkas** [comment]
Yes, this is definitely a bug, thanks for spotting it. Would you mind creating a PR and also adding a check to the tests?

**Comment by wezzle** [comment]
I've sent in a pull request fixing above issue.

However when using the offline scope and receiving the refresh_token the exp is not set either. I could send in another pull request fixing that issue. I think the best way to solve that is to add `RefreshTokenLifespan` to the compose/config and modifying compose/compose_oauth2.go pass it to the `OAuth2ResourceOwnerPasswordCredentialsFactory`. Is that the correct way to go?

**Comment by arekkas** [comment]
Yes, that should work! Thank you for this

**Comment by wezzle** [comment]
Ok, i'll get on this as soon as possible and i'll submit a new pull request.

**Comment by wezzle** [comment]
I've updated the refresh token expiration into above pull request as i believe it's an extension of this issue. Please review the pull request and let me know if you think anything should be changed.

**Comment by MatthewHartstonge** [comment]
Not sure if related, but I've noticed that the `IssueImplicitAccessToken` handler always seems to default to `&expires_in=3600`  even when `exp` is set differently. In this case, I've set mine to 5 minutes for dev.
If I comment out [flow_authorize_implicit line 67](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_implicit.go#L67) it generates the correct number (300 compared to 3600)

**Comment by arekkas** [comment]
superseded by #180
