### ISSUE TITLE
Refresh token revocation with StatelessJWT

### ISSUE THREAD

**Issue by wezzle** [ory/fosite#154]
When using the `compose.OAuth2StatelessJWTIntrospectionFactory` you'll automatically get the Token revocation error as returned at [this line](https://github.com/ory/fosite/blob/14a18a714c419b31d4bf1341e1017159bc17540f/handler/oauth2/introspector_jwt.go#L42).

Should it not be possible to still revoke refresh tokens if you save them in the database? When using the refresh_token grant together with a storage doing a lookup agains the database for a valid refresh token you might still want to be able to revoke the token, purging it from the database and failing the refresh_token grant with a revoked refresh token.

If this is indeed a bug i would suggest having the `StatelessJWTValidator ` only returning an error when tokenType is not `fosite.RefreshToken`.

The `StatelessJWTValidator` only seems to do introspection on [access tokens](https://github.com/ory/fosite/blob/14a18a714c419b31d4bf1341e1017159bc17540f/handler/oauth2/introspector_jwt.go#L20)

I can send in a PR if desired.

**Comment by wezzle** [comment]
I don't store the access tokens, only the refresh tokens as they are valid for a longer period and therefore being able to revoke them is useful in my opinion.

With the current `RefreshTokenGrantHandler` i'm not sure how else you would be able to validate a token except for storing the signature for later reference as that is the only thing passed to the storage.

So unless there is a way of using JWT for access tokens but another strategy for refresh tokens i don't see any other way than storing the refresh token signatures or rewriting the `RefreshTokenGrantHandler` to Stateless Introspect refresh tokens. The latter not having my preference because of the longer lifespan of refresh tokens.

Or if i'm seeing this wrong entirely please let me know.

**Comment by wezzle** [comment]
You have a valid point saving the JWT to the database defeats the purpose of the JWT. I've set it up like this now, not using the compose helpers but creating the `ResourceOwnerPasswordCredentialsGrantHandler` myself inserting the hmac strategy for the refresh token only.

```
	jwtStrat := compose.NewOAuth2JWTStrategy(pk)
	hmacStrat := compose.NewOAuth2HMACStrategy(config, []byte("some-secret"))

	provider := compose.Compose(
		config,
		store,
		jwtStrat,
		compose.OAuth2ClientCredentialsGrantFactory,
		compose.OAuth2RefreshTokenGrantFactory,
		(func(config *compose.Config, storage interface{}, strategy interface{}) interface{} {
			return &oauth2.ResourceOwnerPasswordCredentialsGrantHandler{
				ResourceOwnerPasswordCredentialsGrantStorage: storage.(oauth2.ResourceOwnerPasswordCredentialsGrantStorage),
				HandleHelper: &oauth2.HandleHelper{
					AccessTokenStrategy: strategy.(oauth2.AccessTokenStrategy),
					AccessTokenStorage:  storage.(oauth2.AccessTokenStorage),
					AccessTokenLifespan: config.GetAccessTokenLifespan(),
				},
				RefreshTokenStrategy: hmacStrat,
				ScopeStrategy:        fosite.HierarchicScopeStrategy,
			}
		}),
		compose.OAuth2TokenRevocationFactory,
		compose.OAuth2StatelessJWTIntrospectionFactory,
	)
```

The problem however still exists that when the `compose.OAuth2StatelessJWTIntrospectionFactory` is enabled the token revocation will still return the error defined in `StatelessJWTValidator `. But i would of course like to have it enabled for the JWT access tokens.

I could of course copy the functionality of `StatelessJWTValidator` but my opinion is that `StatelessJWTValidator ` should not error on RevokeToken but maybe only warn the user of possible misconfiguration. Seems to me this is something that should maybe even be in the docs, not the code?

**Comment by arekkas** [comment]
Yeah I think it's a good idea to put that in the docs. Maybe add a FAQ section in the readme for now? Ultimatively I want to move to gitbook

**Comment by wezzle** [comment]
I can send in a PR on the readme, adding a FAQ section. But do you agree the RevokeToken function should be removed from the StatelessJWTValidator as well?

**Comment by arekkas** [comment]
I have to think about it, removing it might break things because it's no longer compatible with the interface?

**Comment by wezzle** [comment]
I'm positive it wont break anything. The Introspector should not bother with revocation. If you were to have the `OAuth2StatelessJWTIntrospectionFactory` enabled, all revocation request would error because of it. So there is no usecase where you were to have it enabled AND support revocation request.

Removing the RevokeToken function would still enable it to do `IntrospectToken`, thats it's only use. The RevokeToken only notifies people of a possible misconfiguration, the only use case this is interesting is if you were to use the Introspector and try to revoke accesstokens, which of course is not available because they are stateless.

**Comment by arekkas** [comment]
Right, that makes sense!

**Comment by arekkas** [comment]
If you remove the revokation form the JWT strategy, please do it in a new PR so we can keep things separate!
