### ISSUE TITLE
ImplicitGrantStorage never used.

### ISSUE THREAD

**Issue by michaelboke** [ory/fosite#165]
the ImplicitGrantStorage in handler/oauth/flow_authorize_implicit_storage.go is never used.
The flow_authorize_implicit.go hints in comments it should be using this interface but the `AccessTokenStorage` is used instead.

I do recommend to remove the interface `ImplicitGrantStorage` and  update the comments in flow_authorize_implicit.go that AccessTokenStorage is used to persist the AccessToken

**Comment by arekkas** [comment]
👍
