### ISSUE TITLE
Introspect token

### ISSUE THREAD

**Issue by michaelboke** [ory/fosite#169]
There is no token_type property when introspecting token.
Now i cannot distinguish the introspect token result which type of token it is.

Also the authorize code is introspected and returned as a result. This is probably not the most ideal situation because now a authorize_code could be seen as a valid token.

I suggest dropping introspection of authorize codes and add the token_type to the introspect result

**Comment by arekkas** [comment]
The token type is always bearer, it does not distinguish between refresh and access tokens. See [here](https://tools.ietf.org/html/rfc6749#section-7.1)  for more information.

**Comment by arekkas** [comment]
see PR

**Comment by michaelboke** [comment]
Thanks for your comments, but i still have no idea how to distinguish the token types in the introspect endpoint. You have any idea's how i can ?

**Comment by arekkas** [comment]
You receive the tokens types when performing the auth code flow, so you should know which token is what, right?
