### ISSUE TITLE
Check refresh token expiration in HMACSHA strategy

### ISSUE THREAD

**Issue by nikita-v** [ory/fosite#178]
Hi!
Expiration time of refresh token is not checked in HMACSHA strategy.
https://github.com/ory/fosite/blob/master/handler/oauth2/strategy_hmacsha.go#L50

**Comment by arekkas** [comment]
Refresh tokens [do not have](https://tools.ietf.org/html/rfc6749#section-6) an expiry date:

> Because refresh tokens are typically long-lasting credentials used to
   request additional access tokens, the refresh token is bound to the
   client to which it was issued.
