### ISSUE TITLE
Auth Code Token Request from JavaScript Fails due to Basic Auth Requirement and/or Lack of CORS

### ISSUE THREAD

**Issue by joshuarubin** [ory/fosite#179]
I am trying to write a javascript client that implements the 3 legged auth code flow. The client happens to be public, but I think that's irrelevant for this discussion. We need to get a refresh token, so using the implicit flow (which works fine) is not an option.

I am using `XHR` to `POST` to the `/oauth2/token` endpoint after getting the code. The problem with this is two fold:

1. our hydra server is running on a different domain than the javascript app
2. hydra does not provide CORS headers and rejects the `OPTIONS` method

When using `XHR`, `POST` requests require preflight CORS validation if the `Authorization` header is provided (https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests)

Hydra returns `405 (Method Not Allowed)` for `OPTIONS` requests on `/oauth2/token` so this fails. It also doesn't seem to support CORS for anything. It seems like it would be useful to provide this to the user through configuration.

Alternatively, it seems like it should be possible to provide the `client_id` and `client_secret` fields in the body of the request according to the RFC. Without the `Authorization` header, the request would not require CORS.
https://tools.ietf.org/html/rfc6749#section-2.3.1

However, this is not implemented right now, only Basic Auth is supported as shown here:
https://github.com/ory/fosite/blob/master/access_request_handler.go#L58

I have read through the discussion at #78 but felt that this was sufficiently different.

Thanks for your help!

**Comment by arekkas** [comment]
Hey thanks for the report, however, this should probably go in the hydra repository, right?

**Comment by joshuarubin** [comment]
Well it depends. You can update `Fosite.NewAccessRequest` to accept credentials in the body of the request to fix this. However, supporting CORS probably belongs in hydra.

**Comment by joshuarubin** [comment]
Added hydra issue ory/hydra#506

**Comment by arekkas** [comment]
Regarding transmission of client credentials in the request body, this is unfortunately discouraged in the official draft

>  Including the client credentials in the request-body using the two
   parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
   to directly utilize the HTTP Basic authentication scheme (or other
   password-based HTTP authentication schemes).

and while some services use this scheme, it requires weird workarounds in client libraries [such as this one](https://github.com/golang/oauth2/blob/ad516a297a9f2a74ecc244861b298c94bdd28b9d/internal/token.go#L92). I don't think it makes sense to soften up fosite's RFC conformity for everyone, if the only problem is CORS. If using fosite without hydra, the developer is capable of adding a CORS middleware to his routing, so in that case this is a non-issue :)
