### ISSUE TITLE
Missing application/json content-type header on WriteIntrospectionResponse

### ISSUE THREAD

**Issue by kgoto1** [ory/fosite#209]
WriteIntrospectionResponse (L:176 in introspection_response_writer.go)
does not set the header for Content-Type.  It returns a 'text/plain; charset=utf-8' when it should set 'application/json; charset=utf-8'.  
Note: The example documentation also states it should be application/json just above it.

**Comment by arekkas** [comment]
Thank you for the report, that's a bug indeed :)
