### ISSUE TITLE
Support for RFC 7636

### ISSUE THREAD

**Issue by natebrunson** [ory/fosite#213]
I would love to see support for [RFC 7636](https://tools.ietf.org/html/rfc7636) built into Fosite. I currently have some dependency on it for an existing client and it is something would prevent me from using Fosite (via Hydra) for that client until it could be supported. 

If this is something the core team thinks would be a good fit, I'd be willing to contribute a PR.

**Comment by arekkas** [comment]
I think it's a very useful addition and it should be implemented easily. I would love to see a PR. For that, it would be perfect if we could discuss how to approach this first. Have you ever worked with fosite before?

**Comment by natebrunson** [comment]
I have not worked with it before. I've browsed the source a bit, read through the CONTRIBUTING doc, and digging through the go doc now.  I'm not sure I've developed an opinion yet on how to approach it, so I'm all ears.

**Comment by arekkas** [comment]
The only relevant pieces I see are point 4.3 and 4.4 in the spec. I'm quite busy at the moment so I didn't give it a very tough look, but from what I saw we only need to store the code challenge server side and then return it later on.

The [authorize request](https://github.com/ory/fosite/blob/master/authorize_request.go) embeds the [request](https://github.com/ory/fosite/blob/master/request.go) which in turn contains a [list](https://github.com/ory/fosite/blob/master/request.go#L17) of all form values (POST body and GET query params) implying that it will also carry the `code_challenge` if set. Thus, all we really need is a [token endpoint handler](https://github.com/ory/fosite/blob/786b971ca1d36a8f0bd0a5c0bfa798802d5c0c26/handler.go#L26-L34) that looks up if the `code_challenge` is set and executes the appropriate business logic (like setting the right response values) in the request.

I think that should do it!

**Comment by natebrunson** [comment]
Yeah I think it's pretty trivial to implement. Basically if the code_challenge and code_challenge_method come through in the authorization request we need to store that probably alongside any state that is associated with the authorization code. Then when the code is exchanged at the token endpoint the request must also contain the code_verifier, which is used to rebuild the code_challenge using the algorithm defined in the code_challenge_method. I propose fosite only supports the 's256'  challenge method, because the 'plain' method is just a waste of time.

Please excuse the lack of markdown I'm posting late from my phone. Hopefully the underscores did enough to imply that when I'm talking about form parameters. I'll get a PR put together and send it over.

**Comment by arekkas** [comment]
Sounds good, I agree on the s256 part!
