### ISSUE TITLE
ValidateAuthorizeCode uses wrong request in flow_authorize_code_token

### ISSUE THREAD

**Issue by wezzle** [ory/fosite#214]
Hi,

I'm using the authorize_code auth to retrieve a code and then use the code to get an access token via the authorization_code grant. The `HandleTokenEndpointRequest` in `flow_authorize_code_token` has a check to see if the [authorize code is valid](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_token.go#L35). However, this check passes the current request to the `ValidateAuthorizeCode` function on the used strategy. Shouldn't this be the `authorizeRequest` [retrieved from the storage](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_token.go#L26)?

When combining the authorize_code with the HMAC Strategy and then saving the requests' RequestedAt to the database the default AuthorizeCodeLifespan will be checked against the authorization_code grant request instead of the original code retrieval request. Therefore it's not able to determine if the code is expired, [see these lines for the expiration validation](https://github.com/ory/fosite/blob/master/handler/oauth2/strategy_hmacsha.go#L59)

Please let me know if this is indeed an error. I'll be happy to submit a pull request if it is.

Regards,
Wezzle

**Comment by arekkas** [comment]
That looks like a bug indeed. To confirm this, could you also provide a reproducible failing test case (e.g. using the fosite-example repo with certain settings)?

**Comment by wezzle** [comment]
I've looked into it a bit further and forked the fosite example to show the use-case in which the auth code does not expire: [https://github.com/ory/fosite-example/compare/master...wezzle:auth-expire-example](https://github.com/ory/fosite-example/compare/master...wezzle:auth-expire-example)

The expire seems to work as long as you set the expiresAt correctly on the session returned by the storage function `GetAuthorizeCodeSession`. However the reason you will get an expire warning is the check done in flow_authorize_code_token's `PopulateTokenEndpointResponse`, [here](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_token.go#L80). This is because the session returned by the store is set on the current request at this [line](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_token.go#L63)

This means that the check for a valid authorize code in the `HandleTokenEndpointRequest` has no use unless you manipulate the session in your own code before sending it into fosite by using `oauth2.NewAccessRequest`.

So I still think the `HandleTokenEndpointRequest`'s `ValidateAuthorizeCode` should use the requester returned by the storage instead of the current one.

The case described above where the expire does work is fully dependent on the session's expiresAt, however the check done in the HMAC strategy using the request's requestedAt when the session has no expiresAt is never ran.

I hope this all makes sense, let me know if you need another example or a more detailed description.

**Comment by arekkas** [comment]
Thank you for the investigation, this all makes sense, I'd happily accept a PR!

**Comment by arekkas** [comment]
Ok, so this has been open for a while and I took another pass at it. To me, the current code looks like it *should* work as the session reference in both `request` and `authorizeRequest` should be the same (both should be pointers pointing to the same register). But it's of course possible that the storage implementation doesn't actually work like that so it does make sense to use the `authorizeRequest` here instead.

**Comment by aeneasr** [comment]
This is resolved
