### ISSUE TITLE
Trouble using JWTStrategy

### ISSUE THREAD

**Issue by cstrahan** [ory/fosite#229]
Following the example at https://github.com/ory/fosite-example, I'm trying to tweak things so that I can use the `JWTStrategy`, but I'm running into some trouble. Hopefully this will suffice to show what I'm trying to do:

```go
var strat = compose.CommonStrategy{
	CoreStrategy: compose.NewOAuth2JWTStrategy(
		mustRSAKey(),
		compose.NewOAuth2HMACStrategy(config, []byte("some-super-cool-secret-that-nobody-knows")),
	),
	OpenIDConnectTokenStrategy: compose.NewOpenIDConnectStrategy(mustRSAKey()),
}
```

```go
func newSession(userDN string) *oauth2handler.JWTSession {
	return &oauth2handler.JWTSession{
		JWTClaims: &jwt.JWTClaims{
			Issuer:    "https://fosite.my-application.com",
			Subject:   userDN,
			Audience:  "https://my-client.my-application.com",
			ExpiresAt: time.Now().Add(time.Hour * 6),
			IssuedAt:  time.Now(),
		},
	}
}
```

When I, for example, try to perform an authorization code grant, my callback attempts to exchange the authorize code for an access token but I get the following error:

> Error occurred in NewAccessResponse: Failed to generate id token because session must be of type fosite/handler/openid.Session

Is there anything immediately apparent that I'm doing wrong? This is with version 0.13.0.

**Comment by cstrahan** [comment]
If switch back to using `openid.DefaultSession`:

```go
func newSession(userDN string) *openid.DefaultSession {
	return &openid.DefaultSession{
		Claims: &jwt.IDTokenClaims{
			Issuer:    "https://fosite.my-application.com",
			Subject:   userDN,
			Audience:  "https://my-client.my-application.com",
			ExpiresAt: time.Now().Add(time.Hour * 6),
			IssuedAt:  time.Now(),
		},
	}
}
```

I get:

> Error occurred in NewAccessResponse: Session must be of type JWTSessionContainer: The authorization server encountered an unexpected condition that prevented it from fulfilling the request

**Comment by cstrahan** [comment]
Ah, I suspect `NewOpenIDConnectStrategy` is what I'm looking for:

``` go
func NewOpenIDConnectStrategy(key *rsa.PrivateKey) *openid.DefaultStrategy {
	return &openid.DefaultStrategy{
		RS256JWTStrategy: &jwt.RS256JWTStrategy{
			PrivateKey: key,
		},
	}
}
```

**Comment by cstrahan** [comment]
... actually, that doesn't give me a `oauth2.CoreStrategy`, so that's not it ...

**Comment by cstrahan** [comment]
So I'm getting closer, I think. This combination successfully lets me use JWT tokens with HS256:

```go
var strat = compose.CommonStrategy{
	CoreStrategy: compose.NewOAuth2HMACStrategy(config, []byte("some-super-cool-secret-that-nobody-knows")),
	OpenIDConnectTokenStrategy: compose.NewOpenIDConnectStrategy(mustRSAKey()),
}
```

```go
func newSession(userDN string) *oauth2handler.JWTSession {
	return &oauth2handler.JWTSession{
		JWTClaims: &jwt.JWTClaims{
			Issuer:    "https://fosite.my-application.com",
			Subject:   userDN,
			Audience:  "https://my-client.my-application.com",
			ExpiresAt: time.Now().Add(time.Hour * 6),
			IssuedAt:  time.Now(),
		},
	}
}
```

Is it possible to use RS256 with a JWTSession? I'm not having any luck figuring that out.

**Comment by arekkas** [comment]
If you want JWT you need

```
var strat = compose.CommonStrategy{
	CoreStrategy: compose.NewOAuth2JWTStrategy(
		mustRSAKey(),
		compose.NewOAuth2HMACStrategy(config, []byte("some-super-cool-secret-that-nobody-knows")),
	),
	OpenIDConnectTokenStrategy: compose.NewOpenIDConnectStrategy(mustRSAKey()),
}
```

The HMAC strategy is used for refresh tokens and authorize codes, the JWT one for access tokens.

Also you must use [this session](https://github.com/ory/fosite/blob/master/handler/openid/strategy_jwt.go#L38) or rather implement [that one](https://github.com/ory/fosite/blob/master/handler/openid/strategy_jwt.go#L30).

The example has not been updated in a while, and JWT is a bit tricky when it comes to oauth2. In general it's advised to not issue transparent tokens (like JWT) but opaque ones (as in HMAC).

**Comment by andrexus** [comment]
I have the same issue. Now the question is whether it is possible to use **openid.DefaultSession** for issuing JWT access tokens and ID tokens at the same time?

**Comment by aeneasr** [comment]
Yes you can issue both at the same time.

**Comment by razer96** [comment]
So, I also have faced this issue. How to implement usage of JWT access and id tokens and HMAC refresh token???

**Comment by aeneasr** [comment]
Check the Hydra source code, we're using that there.

**Comment by rezanouri87** [comment]
Have you guys figured this out?

**Comment by mitar** [comment]
I think the answer is in this file: https://github.com/ory/hydra/blob/master/oauth2/session.go

**Comment by mitar** [comment]
A very simple example:

```
type OAuthSession struct {
	Subject   string
	ExpiresAt map[fosite.TokenType]time.Time
}

func (s *OAuthSession) GetJWTClaims() jwt.JWTClaimsContainer {
	return &jwt.JWTClaims{
		Subject: s.Subject,
	}
}

func (s *OAuthSession) GetJWTHeader() *jwt.Headers {
	return &jwt.Headers{}
}

func (s *OAuthSession) IDTokenClaims() *jwt.IDTokenClaims {
	return &jwt.IDTokenClaims{
		Subject: s.Subject,
	}
}

func (s *OAuthSession) IDTokenHeaders() *jwt.Headers {
	return &jwt.Headers{}
}

func (s *OAuthSession) SetExpiresAt(key fosite.TokenType, exp time.Time) {
	if s.ExpiresAt == nil {
		s.ExpiresAt = make(map[fosite.TokenType]time.Time)
	}

	s.ExpiresAt[key] = exp
}

func (s *OAuthSession) GetExpiresAt(key fosite.TokenType) time.Time {
	if s.ExpiresAt == nil {
		s.ExpiresAt = make(map[fosite.TokenType]time.Time)
	}

	_, ok := s.ExpiresAt[key]
	if !ok {
		return time.Time{}
	}
	return s.ExpiresAt[key]
}

func (s *OAuthSession) GetUsername() string {
	return ""
}

func (s *OAuthSession) GetSubject() string {
	if s == nil {
		return ""
	}

	return s.Subject
}

func (s *OAuthSession) Clone() fosite.Session {
	if s == nil {
		return nil
	}

	return deepcopy.Copy(s).(fosite.Session)
}
```

**Comment by mitar** [comment]
I think this issue can be closed?

**Comment by aeneasr** [comment]
Yup, thanks!
