### ISSUE TITLE
Showing debug information in error formatting

### ISSUE THREAD

**Issue by kujenga** [ory/fosite#251]
In the new way that errors are handled with [RFC6749Error](https://godoc.org/github.com/ory/fosite#RFC6749Error) structs, the logging I have setup with fosite has become significantly less useful.

In particular, the `Error() string` function does not provide anything other than the error name, and none of the formatting methods display the description or the debug information.

I can add custom handling at all sites where errors are logged to do type assertions on the error to log the proper fields, but it seems like it would be nicer if the default format contained these messages. Let me know if I'm missing something!

**Comment by arekkas** [comment]
> I can add custom handling at all sites where errors are logged to do type assertions on the error to log the proper fields, but it seems like it would be nicer if the default format contained these messages.

That's unfortunately the way to go in Go (pun not intended). It's how you handle stack traces too. Logging the debug message as part of the error message can have unintended consequences - for example when printing the message to users where you don't want to have debug messages included.

Hope that helps!

**Comment by kujenga** [comment]
Fair enough, I was able to resolve our issues by adding some helper functions to augment our logging. Closing 👍
