### ISSUE TITLE
[Proposal] Introduce jwt.RS256JWTStrategy as an Interface

### ISSUE THREAD

**Issue by someone1** [ory/fosite#252]
It should be really simple to introduce this as an interface:

```go
type JWTStrategyer interface {
	Generate(claims jwt.Claims, header fjwt.Mapper) (string, string, error)
	Validate(token string) (string, error)
	Decode(token string) (*jwt.Token, error)
	GetSignature(token string) (string, error)
	Hash(in []byte) ([]byte, error)
	GetSigningMethodLength() int
}
```

and update references to this to use the interface instead of the struct, like in `handler/openid.DefaultStrategy` and `handler/oauth2.RS256JWTStrategy`

To keep compatibility you can just add the interface as a named parameter, for instance on the openid implementation:

```go
type DefaultStrategy struct {
	RS256JWTStrategy JWTStrategyer 

	Expiry time.Duration
	Issuer string
}
```
Though I admit this isn't ideal.  However, it should be trivial to update existing code for a proper change here.

It would help out a lot in terms of introducing new strategies where you want to extend existing strategies but plug in a different signing mechanism.

**Comment by arekkas** [comment]
I think that makes sense. Instead of having, for example, `oauth2.RS256JWTStrategy`, we would rename that to `oauth2.JWTStrategy` and allow developers to plug RS512 or ECDSA or whatever when desired. It would introduce some breaking changes in the naming, but it shouldn't be too critical as long as it's well documented!

**Comment by someone1** [comment]
I believe the interface was introduced in commit 7ccad77095dbf8d094b2f3151634f074b0903dbc! However, it doesn't look like `handler/openid.DefaultStrategy` and `handler/oauth2.RS256JWTStrategy` types were updated to use it. Are these strategies superseded by the recent changes to fosite?

**Comment by someone1** [comment]
Just saw the commit that updated the `handler/openid.DefaultStrategy` definition to use the interface! Thank you!

Any chance on getting `handler/oauth2.RS256JWTStrategy` updated as well? I noticed the comments mention that the commit resolves this issue but this last type is still dangling.

For reference, you can see the hurdles I had to jump through previously to utilize a different signing method here: https://github.com/someone1/fosite-gcp-oauth2

There is a lot of copy pasta just to swap out the signing mechanism utilized.

**Comment by arekkas** [comment]
Yeah that makes sense!
