### ISSUE TITLE
request: Support Subject Identifier Types & Pairwise Identifier Algorithm

### ISSUE THREAD

**Issue by vvakame** [ory/fosite#259]
I hope to fosite supports Support Subject Identifier Types & Pairwise Identifier Algorithm.
http://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes

If you are interested in this, I will take a look at the code a little more. 😉

**Comment by arekkas** [comment]
Yeah, that sounds interesting! Please lay out a plan here to align the development of a patch :)

**Comment by vvakame** [comment]
@arekkas quite a while time has passed...
But, I just started work on this problem.

It is difficult to rewrite the `Session` interface's Subject at the current interface.
Therefore, I think that it is safe to replace about `openid.DefaultStrategy#GenerateIDToken` return value.
If this happens, there is a problem that the `subject` value doesn't change aboud Session and IDTokenClaims.
However, it seems that there is no problem because the client get the subject from IDToken of GenerateIDToken returns over the network.

In order to realize this, some BREAKING CHANGE requires necessary.

1. Add some getters to OpenIDConnectClient
    a. GetSubjectType
    b. GetSectorIdentifierURI
2. Define PairwiseSubjectIdentifiersStrategy interface and bring it to openid.DefaultStrategy.
    a. It has `CalculateSubject (client openid.OpenIDConnectClient, sectorIdentifier string) string`
    b. Implement DefaultPairwiseSubjectIdentifiersStrategy
3. Adding arguments to compose.NewOpenIDConnectStrategy

I would like to implement it if this plan is accepted.

**Comment by arekkas** [comment]
This has been added to Hydra, you can check the implementation there if you want: https://github.com/ory/hydra/commit/479acd7ea7c758740824eee62cae624aadcb7ba1

**Comment by vvakame** [comment]
wow, really? It's really good news. I'll check it tomorrow. thanks!

**Comment by arekkas** [comment]
Yup, basically we're setting a different subject in the id token than the access token and have one or two checks to see if the client wants a pairwise algorithm.

**Comment by vvakame** [comment]
thank you so much. hydra's implementation is very helpful.
I may have a question later, but I close this issue now. 😉
