### ISSUE TITLE
IDToken/Refresh and expire time

### ISSUE THREAD

**Issue by mvrhov** [ory/fosite#286]
Was the expire time for the IDToken left out on purpose or is this oversight?
At least for the Refresh token I'd say  that it was left out on purpose. as There is nothing about that inside the Config object

**Comment by arekkas** [comment]
You can set the expiry time of the ID token with: [`IDTokenLifespan`](https://github.com/ory/fosite/blob/master/compose/config.go#L38)

**Comment by mvrhov** [comment]
GetIDTokenLifespan is not called from anywhere, that's the reason I'm asking other *Lifespan methods do get called

**Comment by arekkas** [comment]
Ah, seems like the composer doesn't properly pass down this value. The method that should do that is [this one](https://github.com/ory/fosite/blob/master/compose/compose_strategy.go#L58).

**Comment by arekkas** [comment]
Do you think it would be possible to write a few failing test cases for this? That would make it much easier to debug it

**Comment by mvrhov** [comment]
I doubt it. don't know the library enough and testing with go even less. :/
I've used the debugger with breakpoint set inside proper storage function to figure out the above.

**Comment by arekkas** [comment]
Ok, no problem. I've assigned it to me and will try to look at it when I have a bit of downtime, hopefully sometime this weekend.

**Comment by aeneasr** [comment]
This is resolved!
