### ISSUE TITLE
Add documentation on handlers

### ISSUE THREAD

**Issue by aeneasr** [ory/fosite#29]
As pointed out in #28 , handlers are "magic" for newcomers, especially when coming from osin or similar non-extensible OAuth2 frameworks. Handlers however are a key feature in regards to fosite extensibility and should therefore be better documented.

**Comment by otraore** [comment]
I think overall documentation, tutorials and examples would greatly help. I want to use fosite but certain things are just foreign to me. I really like the project though and your work on it so keep that up! But with that aside resources for newcomers would be greatly appreciated.

**Comment by arekkas** [comment]
it will be done, it just needs some time.

I recommend checking out https://github.com/ory-am/hydra/pull/62 (an implementation of fosite) and the [example](https://github.com/ory-am/fosite/tree/master/fosite-example)

**Comment by chenjie4255** [comment]
yes I came from osin and I get totally fuzzy when I look into this project.

BTW, the example above need to be updated to fit latest source code.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
