### ISSUE TITLE
Password grant, which user does the token belong to?

### ISSUE THREAD

**Issue by Philio** [ory/fosite#291]
I plugged in fosite to a new API that we've been working on to use as the authentication layer. We mainly use a password grant from mobile apps so this was the starting point. Initially used dummy responses from my custom storage implementation to make sure everything was working and then started gradually plugging in database support.

Seem to have hit a bit of a snag when it comes to storing the tokens generated... When storing the access token via `CreateAccessTokenSession` I would expect some user identifiable reference to be passed to assign the token to a user but there doesn't seem to be anything like this. The `Username` field in the `Session` seems like a viable option, but it is never populated.

Is this a bug, or have a missed something here?

**Comment by arekkas** [comment]
The `sub` / `Subject` field of a token identifies the resource owner (user).

**Comment by Philio** [comment]
Thanks for the response, it seems like this would have the same issue though, there is no way to populate it with the current storage interfaces?

**Comment by arekkas** [comment]
Yeah, you're right, there isn't currently a way to hydrate the session with the authenticate call. This should definitely be changed.

On a side note, using the ROPC grant is really, really, really bad practice, terrible for security, officially discouraged, and only for legacy environments where you really HAVE TO use this. Read here for more: https://www.ory.sh/oauth2-for-mobile-app-spa-browser

**Comment by Philio** [comment]
> Yeah, you're right, there isn't currently a way to hydrate the session with the authenticate call. This should definitely be changed.

Thanks for clarifying, for now we just populated the username as the subject from the form data which does the trick.

> On a side note, using the ROPC grant is really, really, really bad practice, terrible for security, officially discouraged, and only for legacy environments where you really HAVE TO use this (you don't because this was targeted at legacy apps in ~2011/2012). Read here for more: https://www.ory.sh/oauth2-for-mobile-app-spa-browser

The main problem with alternatives is that a hand off to a web browser is necessary which isn't a particularly nice user experience.

**Comment by arekkas** [comment]
I really recommend reading https://www.ory.sh/oauth2-for-mobile-app-spa-browser - it explains exactly why going through the browser might initially seem like bad user experience, but ultimately greatly enhances it as it prevents serious credential phishing issues from malicious apps. In the future, most mobile devices will improve the oauth2 sign on experience (Google already does it for their own products, iOS kind of too for some) and this will get better.

Having said that, your solution to hydrate the session using the `username` form is totally legit. The reason for the storage provider to not hydrate the session is that this doesn't happen for other storage providers either - as the library has actually no way of assigning the user.

If you feel happy with the current solution I'll close this as a nofix, although it would be good to have some docs explaining this.

**Comment by Philio** [comment]
We actually won't end up using password grants in production, it's just easier to get a prototype up and running using it and we can defer building the full OAuth2 flow into the API until later. We'll probably be using something custom involving a 2FA element for mobile clients, part of the reason we chose this library is that it looked relatively easy to extend.

On this basis, the solution with the username is certainly fine for the time being and if it gets fixed in a later version while we're still using password grant then we can always update it.

**Comment by mitar** [comment]
Should this be closed?
