### ISSUE TITLE
Expand JWTStrategy Interface

### ISSUE THREAD

**Issue by someone1** [ory/fosite#295]
We sometimes need the Key ID of the Public Key used to sign JWT tokens. Adding the following to the [JWTStrategy token interface](https://github.com/ory/fosite/blob/master/token/jwt/jwt.go#L38) would help in these situations: `GetPublicKeyID() (string, error)`

Referencing https://github.com/ory/hydra/issues/960

**Comment by arekkas** [comment]
As discussed in the other issue, I think this should be handled in hydra, as GetPublicKeyID() isn't used here.

**Comment by someone1** [comment]
As discussed, should be kept in hydra.
