### ISSUE TITLE
Validating tokens from a separate microservice

### ISSUE THREAD

**Issue by bjm88** [ory/fosite#301]
Hi - Love this Fosite project, exactly what we were looking for.  Had an architecture question and wanted to ensure it sounds ok security wise.

We are planning to have a microservice for all security (authentication and authorization) and b/c many other services will call this we wanted something really fast, hence looking for a Golang solution.  This implies that once a client has a token, we want them to be able to use it across several other services/subdomain endpoints.  Each of these other services Will call back to the security service to verify the token.  I assume we'll be able to take the inbound requests and formulate a new http request with just the relevant parts for fosite, but would love an example, if its just getting authorization bearer header and user ?  Would it be recommended that each http req needs to call back to verify token or caching entire user permission after first time on local session cache is ok?   Wondering if each service has fosite stack and we setup shared database as storage is that a better architecture to validate locally without extra hop?  

Alternative of course is centrally checked and for each http request, just worried about performance scaling wise of that setup.

**Comment by aeneasr** [comment]
I recommend checking out [ORY Hydra](https://github.com/ory/hydra). For architectural questions that are only valuable to your own company and/or use case, please ask in the [forums](https://github.com/ory/hydra) or [chat](https://www.ory.sh/chat), thank you!
