### ISSUE TITLE
fosite.validateResponseTypes does not allows composite type?

### ISSUE THREAD

**Issue by pierredavidbelanger** [ory/fosite#304]
**Do you want to request a *feature* or report a *bug*?**

bug?

**What is the current behavior?**

I am playing with the lib to create a minimal openid auth server.

I am using the [storage.NewExampleStore()](https://github.com/ory/fosite/blob/master/storage/memory.go#L70) storage.

And one of the hardcoded client define 3 `ResponseTypes` : `[]string{"id_token", "code", "token"}`.

But I am not able to request a `code` AND a `id_token` like this: 

```sh
curl -v 'localhost:8080/oauth2/auth?client_id=my-client&client_secret=foobar&response_type=code%20id_token&scope=openid&state=j17hd63d7eh&redirect_uri=http://localhost:3846/callback'
```

I get this response:

```
< HTTP/1.1 302 Found
< Location: http://localhost:3846/callback?error=unsupported_response_type&error_description=The+authorization+server+does+not+support+obtaining+a+token+using+this+method&error_hint=The+client+is+not+allowed+to+request+response_type+%22code+id_token%22.&state=
< Date: Mon, 24 Sep 2018 21:29:01 GMT
< Content-Length: 0
<
```

I guess it has something to do with the fac that in [fosite.validateResponseTypes](https://github.com/ory/fosite/blob/master/authorize_request_handler.go#L204) you are validating the composite requested `response_type` (ie: `code%20id_token`) against each individual client defined `ResponseTypes`, so it will never matches, unless one request only ONE `response_type`.

**Comment by pierredavidbelanger** [comment]
Or maybe, the client should be defined like this ?

```go
ResponseTypes: []string{"code", "code id_token", "code token", "code id_token token"},
```

**Comment by aeneasr** [comment]
Yes, exactly!

**Comment by pierredavidbelanger** [comment]
So if it is not a bug in `fostite.validateResponseTypes` ? 

Then the [two clients defined here](https://github.com/ory/fosite/blob/master/storage/memory.go#L70) are not correctly configured.

Do you need a PR ?

**Comment by pierredavidbelanger** [comment]
Do you want this lib to be able to support non openid auth2 setup ?

**Comment by aeneasr** [comment]
Not sure what you mean?

**Comment by pierredavidbelanger** [comment]
Sorry :) I mean, with fosite one is able to create an OpenID auth server , with the new `validateResponseTypes` logic. 

My question is, do you want someone to be able, with fosite, to create a plain OAuth2 auth server , with the old logic (ie: all combinations of `{"code", "id_token"}`) ?

**Comment by pierredavidbelanger** [comment]
Oh, I realized while posting this question that fosite already support this, it only a matter of how someone define the clients ..

**Comment by aeneasr** [comment]
Regarding your first question, no, this library will not support the old way of doing it because:

* (as you already realized) it's still possible to get all of the combinations
* we would lose OpenID Connect certification
* it's better to solve it in a way that is defined by an open standard than vendor-specific logic

**Comment by mitar** [comment]
I made https://github.com/ory/fosite/pull/413 to address this issue.
