### ISSUE TITLE
auth code and refresh token flows should be treated as a transaction

### ISSUE THREAD

**Issue by aaslamin** [ory/fosite#309]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

https://github.com/ory/fosite/blob/master/handler/oauth2/flow_refresh.go#L107-L119
https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_token.go#L144-L152

Notice how it is possible for any of those db calls to fail which will leave the authz service and client in a bad state. For example, a client's access/refresh tokens could be revoked and the call to create a new token pair could fail leaving the client very confused.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This is a clear by looking at the code. But to simulate this, you can modify one of the methods in your storage implementation with a long sleep (or return an error intentionally) to inject a fault, re-build your service and go through one of the flows.

For example, Hydra's implementation of the `TokenRevocationStorage` interface is implemented by `FositeSQLStore` - you can modify https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go#L398 to return an error to simulate failure.

**What is the expected behavior?**

These flows should *be all or nothing*. The client should never have to worry about the authorization server messing up.

**Which version of the software is affected?**

All

**Proposal**

Still TBD, but potentially a new method in both https://github.com/ory/fosite/blob/master/handler/oauth2/revocation_storage.go#L30 & https://github.com/ory/fosite/blob/master/handler/oauth2/storage.go#L30 to deal with their respective flows as a TX.

_Cc: @aeneasr @fredbi_

**Comment by aaslamin** [comment]
Sorry haven't had a chance to look into this yet, will pick it up once tracing work is completed.

**Comment by aeneasr** [comment]
No worries, just let me know when you took a glance!

**Comment by aaslamin** [comment]
If I am following correctly, this implies that a storage implementation with transaction support always needs to check first if a transaction object is present (some attribute in the struct) before attempting to fetch a new connection prior to any database operation. Because you won't know if you are dealing with a transaction that may be in progress.

```
type SomeStorageWithTXN interface {
  Begin() (SomeStorage, error)
  Commit() (error)
  Rollback() (error)

  MethodA (Result, error)
}
```


```
// Suppose this struct implements SomeStorageWithTXN
type AmirStore struct {
	DB                  *sqlx.DB
	L                   logrus.FieldLogger
        TXN                 *sql.Tx                 // This must be checked inside the implementation of MethodA
}

func (s *AmirStore) MethodA (api.Result, error) {
        if s.TXN != nil {
             // dealing with a TXN now
             s.TXN.ExecContext(...)
        } else {
             // not dealing with a TXN
            s.DB.ExecContext(...)
        }
}
```

Is this what you were thinking @aeneasr? If so, it seems pretty heavy weight especially considering the amount of copying that will take place. I am not even sure if that will cause problems?

Alternatively I was thinking of having one method in any storage interface that needs to do a set of actions atomically. So for example, in the `TokenRevocationStorage` interface:

```
type TokenRevocationStorage interface {
	RefreshTokenStorage
	AccessTokenStorage

        // NEW METHOD
       	// Do all the things in one step within a transaction if your storage provider
	// supports it.
	RevokeTokensAtomically(ctx context.Context, requestID string) error

	RevokeRefreshToken(ctx context.Context, requestID string) error
	RevokeAccessToken(ctx context.Context, requestID string) error
}
```

But even this is a 💩solution because it is quite vague how to provide an implementation for `RevokeTokensAtomically`. It's benefit is simplicity. It will demand strong documentation.

![](https://media.giphy.com/media/PBg4KWciMK6zu/giphy.gif)

**Comment by aeneasr** [comment]
> If I am following correctly, this implies that a storage implementation with transaction support always needs to check first if a transaction object is present (some attribute in the struct) before attempting to fetch a new connection prior to any database operation. Because you won't know if you are dealing with a transaction that may be in progress.

Not particularly, I think the gif is appropriate if you were to solve it this way. I think we can actually leverage the context here:

```
// in the oauth2 handler thingy
ctx, err := Storage.MaybeCreateTransaction(ctx)
// errors if something went wrong, returns the same context if no transaction support, returns context with transaction if transaction support

Storage.CreateAccessTokenSession(ctx, ...)
// we won't roll back this transaction if it fails, that's the store's responsibility

err := Storage.MaybeCommitTransaction(ctx)
```

I think that would save us a lot of trouble.

**Comment by aeneasr** [comment]
Oh and for memory stores etc. this would simply be a stub:

```
func (s *Storage) MaybeCommitTransaction(_ context.Context) { return nil }
func (s *Storage) MaybeCreateTransaction(ctx context.Context) { return ctx, nil }
```

**Comment by aaslamin** [comment]
Closing as a result of https://github.com/ory/fosite/pull/343
