### ISSUE TITLE
DOCS: Example issue 

### ISSUE THREAD

**Issue by barzoj** [ory/fosite#318]
**To Reproduce**
Steps to reproduce the behavior - just follow example steps 

go get github.com/ory/fosite-example
# github.com/ory/fosite-example/authorizationserver
src/github.com/ory/fosite-example/authorizationserver/oauth2.go:35:45: not enough arguments in call to compose.NewOAuth2HMACStrategy
	have (*compose.Config, []byte)
	want (*compose.Config, []byte, [][]byte)
src/github.com/ory/fosite-example/authorizationserver/oauth2.go:38:62: not enough arguments in call to compose.NewOpenIDConnectStrategy
	have (*rsa.PrivateKey)
	want (*compose.Config, *rsa.PrivateKey)

**Expected behavior**
Examples are expected to compile and run

**Env**
go version
go version go1.11.1 darwin/amd64

**Comment by aeneasr** [comment]
You didn't fetch the right dependencies (dep ensure). This will be fixed with the new go modules PR that's up there: https://github.com/ory/fosite-example/pull/14
