### ISSUE TITLE
Go Report Cleanup

### ISSUE THREAD

**Issue by someone1** [ory/fosite#323]
Wished Go Report integrated with the CI tools, looks like quality has been slipping a bit:
https://goreportcard.com/report/github.com/ory/fosite

Not that I think 100% across the board is required, but I think it could be better than it currently is.

Maybe it makes sense to integrate [golangci](https://golangci.com) as suggested in https://github.com/ory/hydra/issues/1092 (though doesn't seem to have misspell checks)

**Comment by someone1** [comment]
Yes that could work, Go Report uses a misspell linter as well.

I'm partial to [gometalinter](https://github.com/alecthomas/gometalinter) myself, which you can enable the misspell linter for in addition to the many others it can run.

**Comment by aeneasr** [comment]
Closing as noone wants to / can work on this
