### ISSUE TITLE
Add support for key rotation, used for signing ID Token.

### ISSUE THREAD

**Issue by nerocrux** [ory/fosite#329]
**Is your feature request related to a problem? Please describe.**

To make ID Token more secure, I wish to rotate the private key per hour.
However, fosite requires private key to be specified when initialize OpenIDConnectStrategy.
So the private key cannot be changed, unless I reboot my authz server based on fosite.

**Describe the solution you'd like**

I hope fosite can provide an interface which allows users to change private key on runtime, or even provide a key-rotation solution if possible.

fosite should also add a `kid` claim to ID Token Header, which should also be customizable.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by aeneasr** [comment]
Key rotation is a first-class citizen in hydra, check it out over there

**Comment by nerocrux** [comment]
Figured out how to archive that. Thanks!

**Comment by aeneasr** [comment]
Feel free to share your knowledge here or in a PR to the readme :)
