### ISSUE TITLE
Allow users to config AuthCodeEntropy

### ISSUE THREAD

**Issue by nerocrux** [ory/fosite#340]
**Is your feature request related to a problem? Please describe.**

* I understand 32 bytes entropy may be secure enough, but in some cases I may still want to change the entropy (32 bytes -> 64 or 128 bytes) of Token generated using HMAC strategy, which is currently not possible.

**Describe the solution you'd like**

* Make `AuthCodeEntropy` configurable for NewOAuth2HMACStrategy()
    * https://github.com/ory/fosite/blob/master/compose/compose_strategy.go#L41

**Describe alternatives you've considered**

* None.

**Additional context**

* Maybe also should give this value a upper limit, like 256 (int).
* If this sounds OK, I'll create a pull request. Thanks for reviewing.

**Comment by aeneasr** [comment]
Yup sounds good

**Comment by nerocrux** [comment]
Thank you! I will implement this.

**Comment by nerocrux** [comment]
PR created.
https://github.com/ory/fosite/pull/342

**Comment by nerocrux** [comment]
Implemented so I'm gonna close this issue.
Thanks!
