### ISSUE TITLE
introspect: merge token info before return error when evaluating scopes

### ISSUE THREAD

**Issue by thiagocaiubi** [ory/fosite#341]
Hello! First, thanks for fosite. 

**Is your feature request related to a problem? Please describe.**

I was wondering if there is any way to return `AccessRequest` merged even when a token is being invalidated due to invalid scope. Logs and metrics could be more detailed when calling `IntrospectToken` and receiving an error. For example, a metric could be emitted to statsd or prometheus with the `client_id` which initiated the request.

Although I'm not sure this is the right way to authorise a follow-up request once a token was emitted.

**Describe the solution you'd like**

Example about access token introspection.

From:

https://github.com/ory/fosite/blob/211b43b4c04c732adc5fbfa7cab339f44fbea7d7/handler/oauth2/introspector.go#L81-L96

To:

```
func (c *CoreValidator) introspectAccessToken(ctx context.Context, token string, accessRequest fosite.AccessRequester, scopes []string) error {
	sig := c.CoreStrategy.AccessTokenSignature(token)
	or, err := c.CoreStorage.GetAccessTokenSession(ctx, sig, accessRequest.GetSession())
	if err != nil {
		return errors.WithStack(fosite.ErrRequestUnauthorized.WithDebug(err.Error()))
	} else if err := c.CoreStrategy.ValidateAccessToken(ctx, or, token); err != nil {
		return err
	}

        accessRequest.Merge(or)

	if err := matchScopes(c.ScopeStrategy, or.GetGrantedScopes(), scopes); err != nil {
		return err
	}

	return nil
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks!

**Comment by aeneasr** [comment]
Sorry, this slipped my notifications. I'm not sure about this, client id and other things should already be available from the initial request, right? I'm also not sure if it makes sense to treat e.g. the validation (`ValidateAccessToken`) and dbal (`GetAccessTokenSession`) differently from matchScopes?
