### ISSUE TITLE
There is no way to fobidden client to use any of `prompt` parameters.

### ISSUE THREAD

**Issue by nerocrux** [ory/fosite#348]
**Describe the bug**

There is no way to fobidden client to use any of `prompt` parameters.
Even if we intentionally set `AllowedPromptValues` to nil in config, fosite will treat it as `USING DEFAULT VALUE` instead of forbidden all values.

**To Reproduce**
1. (authz server) set `AllowedPromptValues` to `nil` or `[]string{}`
2. (client) send authorize request with `prompt` parameter, which has any value of `none, consent, login or select_account`
3. (client) authorize request is valid, and prompt behavior follows client's request

**Expected behavior**
Since we don't want to allow client to override prompt behavior, we hope to see `invalid_request` error.

**Screenshots**
None

**Version:**
 - Environment: all
 - Version: all

**Additional context**

As I have discussed in discord.
The validation of `AllowedPromptValues` is not good enough I think.
I propose the following modification.
https://github.com/ory/fosite/compare/master...nerocrux:nerocrux/fix_allowed_prompt_validation

Thanks in advance.

**Comment by aeneasr** [comment]
While the change is minimal with the expected behavior, this is a very serious breaking change which is extremely hard to catch because `[]string{}` and `var f []string` are almost identical. As a workaround you could set `AllowedPromptValues: []string{"disabled"}` which will have the same effect.

**Comment by nerocrux** [comment]
> this is a very serious breaking change
OK, I have to admit this.
Looks like we have to use this workaround you suggested.
Thanks!
