### ISSUE TITLE
Is fosite production ready ?

### ISSUE THREAD

**Issue by spy16** [ory/fosite#350]
I am considering to use `fosite` in an AuthN/AuthZ system for a company and have few questions.

1. Are there any benchmarks or data that can be provided from any production systems based on fosite ?
2. I believe Hydra internally uses Fosite, which means the performance descriptions provided in the ory [documentation](https://www.ory.sh/docs/performance/hydra) should roughly apply to fosite. Correct me if i am wrong.

**Comment by aeneasr** [comment]
Yes and yes

**Comment by aeneasr** [comment]
Yes and yes
