### ISSUE TITLE
scope in access token is not space delimited

### ISSUE THREAD

**Issue by zhuowang10** [ory/fosite#362]
Scope is hard corded as "scp" in access token, and its format is not space delimited string but a string list. 
Although scope name and format in access token is not defined in jwt token standard (https://tools.ietf.org/html/rfc7519#page-9), scope in oauth2 request/response is defined as space delimited string (https://tools.ietf.org/html/rfc6749#section-3.3). 
Can we expose functions to customize the name and format of scope in access token?

**Comment by aeneasr** [comment]
An OIDC related spec lists the scope as `scp` and as an array which is why we're using that format here. I think it should be straight forward to extend the concrete implementation for that feature if you'd like to have it as `scope` with space-delimited string.

**Comment by zhuowang10** [comment]
Thanks for the quick response.
Do you mind to point out which oidc related spec you mentioned? I'm trying to find the standard to decide which format to use, and didn't find out yet.

**Comment by mitar** [comment]
Was it [maybe this document](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-03#section-4.2)? Because that is just a draft. In final standard, [`scope`](https://tools.ietf.org/html/rfc8693#section-4.2) is used and it is a not an array.

**Comment by aeneasr** [comment]
I don't think we will "fix" the current `scope` (we could add a new field though!) because it's going to be breaking with pretty hard implications for e.g. access control proxies. Might make it configurable of course but not sure how useful that really is? I'd actually prefer to have just one spec.

**Comment by mitar** [comment]
> because it's going to be breaking with pretty hard implications

But it will be failing closed. So this should not open any access.

So decide what should be here. Current `scp` field is not in any spec/standard. `scope` is. If you want to be standard compliant, you should or:
* Rename/change.
* Add a new field.
* Make it configurable.

Which one? I can try to make a PR, but should know which approach you want.

> I'd actually prefer to have just one spec.

So `scope` then and breaking compatibility?

Is there any other spec which uses `scp` and array of values?

**Comment by aeneasr** [comment]
No, adding `scope` is fine - I thought that's the case already. I wrote Fosite years ago so I actually don't remember all the details anymore ;)

Adding `scope` with a space-delimited string is fine from my end!

**Comment by mitar** [comment]
No, it is just `scp`: https://github.com/ory/fosite/blob/4e4121bac5cda8efa7d3eb6aaf7720f3ff59c329/token/jwt/claims_jwt.go#L104-L106

**Comment by mitar** [comment]
Can we also make a configuration option to not add `scp`? To keep JWTs small?

**Comment by aeneasr** [comment]
We could also just make the scope key configurable

**Comment by mitar** [comment]
I mean, the value of scope key is different based on the name. :-)

So I propose configuration option which is enum to select between `scp`, `scope`, or both? Not sure how to get that setting to [here](https://github.com/ory/fosite/blob/4e4121bac5cda8efa7d3eb6aaf7720f3ff59c329/token/jwt/claims_jwt.go#L104-L106) though.

**Comment by aeneasr** [comment]
> I mean, the value of scope key is different based on the name. :-)

True, but also different per specification ;) But let's go with a simple solution first, I think the enum sounds good!

Hm, maybe a `WithScope(key string, value string)` function for the JWTClaims? Then set that whereever the JWT is generated?
