### ISSUE TITLE
[Discussion] Implement consent interface

### ISSUE THREAD

**Issue by nerocrux** [ory/fosite#369]
**Is your feature request related to a problem? Please describe.**

When I implementing my IDP with fosite, I'll need to manage user consents by myself.
What I'm trying to do is to store `when did the user (subject) authorized what scope` to DB.
I can collect these information by aggregate AT/RT records, but this will be pretty tough.

Why I doing this is because using these information, I can allow users to skip authorization for certain scopes, if they already authorized these in a short period.

I can also revoke certain consents of scopes to make user authorize again.

**Describe the solution you'd like**

Offer an user consent interface. User can get/save information about when / what scope they have authorized, by subject.

The `consent` struct might look like this.

```
type Consent struct {
   ID string
   ClientID string
   Subject string
   Scope string
   GrantedAt time.Time
   RevokedAt  time.Time
   ExpiresAt  time.Time
}
```

The interface itself might look like this.

```
type UserConsentStorage interface {
        CreateUserConsentSession(ctx context.Context, request fosite.Requester) (err error)

        GetUserConsentSession(ctx context.Context, session fosite.Session) (request fosite.Requester, err error)
}
```

This could also be useful when implementing incremental authorization.

* https://tools.ietf.org/html/draft-ietf-oauth-incremental-authz-02
* https://developers.google.com/identity/sign-in/web/incremental-auth

**Describe alternatives you've considered**

**Additional context**

**Comment by aeneasr** [comment]
Consent can have many facettes, it may not only include the scope, but also an audience, additional metadata, maybe the device where the request came from. I'm not sure this is generalizable enough to be in here.
