### ISSUE TITLE
OpenID Connect audit

### ISSUE THREAD

**Issue by arekkas** [ory/fosite#37]
Fosite's vision is to be a security first framework for OAuth2 related standards. I can not audit everything on my own, so I need your help to find issues and missing features which are required for this vision.

**Comment by jmwong** [comment]
@arekkas what do you think about creating a reference implementation and put it through the conformance tests: http://openid.net/certification/testing/?

**Comment by arekkas** [comment]
sounds good!

**Comment by arekkas** [comment]
We'll be doing that as part of hydra!
