### ISSUE TITLE
Add configuration to return refresh tokens without requiring "offline" or "offline_access" scopes

### ISSUE THREAD

**Issue by dmcinnes** [ory/fosite#370]
**Is your feature request related to a problem? Please describe.**

Hello! I've started working on a PR for this but I should first see if it fits in with your roadmap.

We have a requirement for our service to always return refresh tokens with authorization code grant exchange, however the fosite library requires the `offline` or `offline_access` scopes. For our needs it would be great if the scope is not required.

**Describe the solution you'd like**

An additional bool configuration to the [compose.Config struct](https://github.com/ory/fosite/blob/master/compose/config.go#L31-L89) to turn on always returning refresh tokens. This would need to be passed down to the relevant handlers.

**Describe alternatives you've considered**

An alternative for us would be to modify existing requests to insert the "offline_access" scope, however this is not ideal if we expose the authorizations and their scopes elsewhere.

**Additional context**

I will happily submit a PR if you are are to this idea (I already have one in progress as mentioned above).

**Comment by aeneasr** [comment]
How about a field `RefreshTokenScope: []string` which is per default `offline` / `offline_access` but can be left empty or set to empty to disable the scope. Please keep in mind that this change **must** be backwards compatible.

**Comment by dmcinnes** [comment]
@aeneasr Ah I like it! I'll get that a go, thanks!

**Comment by mitar** [comment]
I think this has been done?
