### ISSUE TITLE
ory hydra token handler is failing as the client_secret is compared to a hashed value in Fosite

### ISSUE THREAD

**Issue by arno-joule** [ory/fosite#385]
**Describe the bug**

While attempting to retrieve a token I get a 401 `HTTP/1.1 401
Content-Type: application/json
{
  "error": "invalid_client",
  "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)",
  "status_code": 401
}`

I hunted down the issue to a log entry 
`ERRO[267507] An error occurred debug="crypto/bcrypt: hashedPassword is not the hash of the given password" description="Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)" error=invalid_client`

**To Reproduce**

1. set up in memory ory/Hydra 
`go get -d -u github.com/ory/hydra
cd $GOPATH/src/github.com/ory/hydra
make init
export GO111MODULE=on
## Without database
make quicktest

Then run it with in-memory database:

DSN=memory go run main.go serve all`

2. run curl to create a test client (fairly standard) using oidcdebugger.com
`curl -X POST \
  https://localhost:4445/clients/ \
  -H 'Accept: application/json' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 414' \
  -H 'Content-Type: text/plain' \
  -H 'Host: localhost:4445' \
  -H 'Referer: https://localhost:4445/clients/' \
  -H 'User-Agent: PostmanRuntime/7.16.3' \
  -d '{
        "client_id": "test",
        "client_name": "test",
        "redirect_uris": [
            "https://oidcdebugger.com/debug"
        ],
		  "response_types": [
		     "code",
		     "id_token"
		  ],
		  "grant_types": [
		     "authorization_code",
		     "refresh_token"
		  ],
        "scope": "openid offline",
        "secret": "123456789",
        "token_endpoint_auth_method":"client_secret_post"
}'`

3. run a curl to retrieve the token (I realize this is not Oauth flow but it triggers the issue)

`curl -X POST \
  https://localhost:4444/oauth2/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=test&client_secret=123456789&grant_type=authorization_code&code=WoIv8eHmvndht_r9LrX_Z90lV9Edc5sxMXxDl5tu_-8.6ka2froWG0BzDbvaO5gi71xrEADAYZvjWpZhMfIWqcw&redirect_uri=https%3A%2F%2Fopenidconnect.net%2Fcallback'`

4. At line 203 of client_authentication.go
`	// Enforce client authentication
	if err := f.Hasher.Compare(ctx, client.GetHashedSecret(), []byte(clientSecret)); err != nil {
		return nil, errors.WithStack(ErrInvalidClient.WithDebug(err.Error()))
	}`

The hashed secret is retrieved and then compared to the clientSecret (which is not hashed and Hydra doesn't provide the hashed value back - which would defeat the purpose of a hashed password) - and of course this will never work.

**Expected behavior**

The client_secret passed should be hashed and then compared with the stored hashed password.

**Environment**

* Version: fosite@v0.30.0
* Environment: tested in Docker (K8S, and OS X)

**Additional context**

Created as well on the fosite issue tracker as it is an issue that impacts hydra https://github.com/ory/hydra/issues/1580

**Comment by ximbal** [comment]
Experiencing the same issue, please help.

**Comment by aeneasr** [comment]
Your analysis is incorrect, that's not how BCrypt works (check the method signature). For more help check https://github.com/ory/hydra/issues/1580
