### ISSUE TITLE
JWT token introspection takes 0.8s

### ISSUE THREAD

**Issue by pietercardoen** [ory/fosite#390]
I am trying to setup token introspection with jwt tokens. I am able to obtain a token and introspection succeeds successfully but the introspection takes way too long. 0.8s for each request.

What can I do to reduce the time needed by fosite to execute the introspection?

This is my introspect handler:
func introspectEndpoint(rw http.ResponseWriter, req *http.Request) {
	ctx := fosite.NewContext()
	mySessionData := newSession("")
	ir, err := oauth2.NewIntrospectionRequest(ctx, req, mySessionData)

	// Hook not compliant with RFC 7662 - NGINX decides based on HTTP reply status
	if !ir.IsActive() {
		rw.WriteHeader(http.StatusUnauthorized)
	}

	if err != nil {
		log.Printf("Error occurred in NewAuthorizeRequest",err)
		oauth2.WriteIntrospectionError(rw, err)
		return
	}

	oauth2.WriteIntrospectionResponse(rw, ir)
}

**Comment by aeneasr** [comment]
That is very unusual. What algorithm are you using, how many bits, etc? I recommend doing a Go Memory an CPU profile - I’m pretty confident this isn’t Fosite‘s fault - we’ve never observed this magnitude of latency in the 5 years of Fosite.

**Comment by pietercardoen** [comment]
Dear

Thanks for your reply. I'm quite new to golang and didn't know the memory/cpu profiling!

I forgot to inform that I am using this on a Xilinx Zynq embedded platform.

The CPU profiling made already something clear:
Showing top 10 nodes out of 15
      flat  flat%   sum%        cum   cum%
   11320ms 91.51% 91.51%    11320ms 91.51%  golang.org/x/crypto/blowfish.encryptBlock
     840ms  6.79% 98.30%    12160ms 98.30%  golang.org/x/crypto/blowfish.ExpandKey
         0     0% 98.30%    12240ms 98.95%  github.com/gorilla/mux.(*Router).ServeHTTP
         0     0% 98.30%    12160ms 98.30%  github.com/ory/fosite.(*BCrypt).Compare
         0     0% 98.30%     2360ms 19.08%  github.com/ory/fosite.(*Fosite).AuthenticateClient
         0     0% 98.30%     2360ms 19.08%  github.com/ory/fosite.(*Fosite).NewAccessRequest
         0     0% 98.30%     9850ms 79.63%  github.com/ory/fosite.(*Fosite).NewIntrospectionRequest
         0     0% 98.30%    12160ms 98.30%  golang.org/x/crypto/bcrypt.CompareHashAndPassword
         0     0% 98.30%    12160ms 98.30%  golang.org/x/crypto/bcrypt.bcrypt
         0     0% 98.30%    12160ms 98.30%  golang.org/x/crypto/bcrypt.expensiveBlowfishSetup

I will continue investigating this.

**Comment by aeneasr** [comment]
Right - BCrypt is slow by design. I recommend using another access token in the Authorization header instead of Basic Authorization

**Comment by pietercardoen** [comment]
What kind of token do you recommend to use?

**Comment by aeneasr** [comment]
Introspection expects either `Authorization: basic base64(<clientid>:<clientsecret>)` or `Authorization: bearer <access-token>` to authorize the request to the introspection itself, and the actual token you want to introspect in the POST body `token=<access-token>`.

I recommend using `bearer` instead of `basic` on embedded systems.

**Comment by pietercardoen** [comment]
I've just configured a bearer token to be used for introspection in my reverse proxy. Apparently, the introspect is a magnitude faster.

Thanks


I will close this issue.
