### ISSUE TITLE
Misconfiguration error when not including "openid" scope

### ISSUE THREAD

**Issue by nerocrux** [ory/fosite#397]
I considered to post this to community forum, but I think this deserves an issue.

--

When I send authorize request without "openid" scope (response_type=code), the auth_code will be issued, but when I send token request, an "misconfiguration" error with http status 500 will return.

Is this expected behaviour?

The OIDC spec defines that you must add a "openid" scope in authorize request, so maybe we should return error in authorize request.

If you want to treat such request as a OAuth2 request, not an openid one, maybe you should not return 500 error, but an 400 one, in token response.

-- 

Edit: 
If I remove `OpenIDConnectExplicitFactory` from compose.Compose(), then AccessToken, RefreshToken will be issued properly. But if I add `OpenIDConnectExplicitFactory`, then the Misconfiguration Error in OpenIDConnectExplicitHandler will occur everytime, even openid scope is not granted.

**Comment by mitar** [comment]
I think this is an issue on your side.
