### ISSUE TITLE
Support "keys" endpoint

### ISSUE THREAD

**Issue by mitar** [ory/fosite#407]
**Is your feature request related to a problem? Please describe.**

It is useful to provide public keys to validate signatures on the server directly. Currently, one has to provide such endpoint manually.

**Describe the solution you'd like**

Provided `request` and `response` function to used to implement a handler. Information is available in the RSA key provided to fosite.

**Additional context**

Example: https://developer.okta.com/docs/reference/api/oidc/#keys

**Comment by aeneasr** [comment]
Yeah, we can use the storage to fetch all available keys. This is implemented in Hydra so it can probably just be copied here.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
