### ISSUE TITLE
Support introspection of ID tokens

### ISSUE THREAD

**Issue by mitar** [ory/fosite#410]
**Is your feature request related to a problem? Please describe.**

It looks like introspection of ID tokens does not work through the introspect handler?

**Describe the solution you'd like**

That it does.

**Describe alternatives you've considered**

I could validate ID tokens locally by myself, but it is also useful to have an API endpoint to do so.

**Additional context**

Okta does so: https://developer.okta.com/docs/reference/api/oidc/

**Comment by aeneasr** [comment]
Is there an open standard to this? I don't quite remember but I think some OpenID Connect spec was covering this. Maybe it would make sense to go down that road? The okta solution seems to be "proprietary" to their API.

**Comment by mitar** [comment]
So [rfc7662](https://tools.ietf.org/html/rfc7662) just covers access and refresh tokens, others are out of the scope. But it is dealing only with OAuth anyway. I could not find anything about ID token introspection in OpenID Connect specs. But that is a bit strange, given that OIDC adds a new token type. So not sure what to do about this.

**Comment by aeneasr** [comment]
The rationale is that there is no need to do introspection if the token is not opaque and you have access to the keys. This seems to be really dependent on the provider, Google has the tokeninfo endpoint for that which doesn't follow any RFC or OIDC convention.

**Comment by mitar** [comment]
For my use case, it is more about validation than introspection. One can always decode it, but to check if token was not revoked, you have to call introspection endpoint, no? So it is about trusting the authorization server to do the validation instead of you doing it locally. For some use cases where you do not care so much about extra round trip time, this might be OK.

See [also this spec](https://tools.ietf.org/html/draft-ietf-oauth-jwt-introspection-response-08). This is not exactly the same thing as we are discussing here, but has some of similar rationale for it:

> However, there are use cases where the resource server requires stronger assurance that the authorization server issued the token introspection response for an access token, including cases where the authorization server assumes liability for the content of the token introspection response.

This is similar to what I am thinking. I want the server to tell me that everything is OK. That it is not the client who has the clock wrong, or that the token was revoked.

Is there any other endpoint to check if an ID token has been revoked?

**Comment by aeneasr** [comment]
> For my use case, it is more about validation than introspection. One can always decode it, but to check if token was not revoked, you have to call introspection endpoint, no? So it is about trusting the authorization server to do the validation instead of you doing it locally. For some use cases where you do not care so much about extra round trip time, this might be OK.
>
> Is there any other endpoint to check if an ID token has been revoked?

ID Tokens can not be revoked. They are proof that someone logged in and is who they say they are with a timestamp of when that happened. ID Tokens do not establish a shared "login" session between the RP and OP.

**Comment by mitar** [comment]
You are right. There is whole set of [other specs](https://openid.net/specs/openid-connect-session-1_0.html) about session management and ways to logout. In fact, checking with `none` response type (#409) is one of ways to determine if user is still logged in.

**Comment by aeneasr** [comment]
Yup - so I take it this can be closed then?

**Comment by mitar** [comment]
I mean, I would still like to have this in, like Okta does, so that one can call it to verify the token, like I wrote above:

> This is similar to what I am thinking. I want the server to tell me that everything is OK. That it is not the client making this decision, which might have the clock wrong (on purpose or by mistake) to have token expiration badly checked. 

It is true that this does not check for revocation, as you cannot revoke ID tokens, as you explained to me. But the rest, that you can offload token validation to server, I find it still useful. (For example, I use Kong and have a Kong plugin, so if I can just call my server to validate the token it seems much easier than encoding token validation in the plugin.)

**Comment by aeneasr** [comment]
The core problem I see is that the OAuth2 Token Introspection spec is targeted at Resource Servers. So when a Resource Server receives a token, it checks against the Authorization Server if the token is (still) valid and what its payload is. The payload is typical internal session state and might contain things like roles, permissions, and so on. Because this stuff is "internal" and confidential in 99% of use cases, Introspection is typically not exposed to the outside world. For me at least I don't know any big OAuth2 Providers (not talking about IDaaS like Auth0) where this is implemented according to spec. Some providers do have a check token endpoint though.

That's why Hydra exposes this endpoint at the Admin API only!

However, ID Tokens are external readable state (per definition because JWT). It therefore - for me - contradicts what OAuth2 Token Introspection solves and may confuse people into exposing the OAuth2 Token Introspection to the outside world.

Keep in mind that the Access Token is something that's only useful on the Resource Server side. The client doesn't really care what it's content is as long as it gives access to something. This is different from what an ID Token represents.

I think Google has an endpoint to decode/verify ID Tokens - maybe they follow some spec?

**Comment by mitar** [comment]
You are right, they have [tokeninfo](https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint) endpoint. It is [mentioned here as well](https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/). That looks to me like introspect endpoint in fact, like what I am requesting here, if I just open https://oauth2.googleapis.com/tokeninfo I get:

```
{

    "error": "invalid_token",
    "error_description": "Either access_token, id_token, or token_handle required"

}
```

But I do not see any standard being referenced anywhere. It just returns parsed ID token it seems (if validated).

Thanks for explaining more here though. I completely agree with everything you wrote. I see this really just as a debug tool and something one can quickly use to make sure things work. Calling this endpoint on regular basis is unnecessary load anyway.

**Comment by mitar** [comment]
> Because this stuff is "internal" and confidential in 99% of use cases, Introspection is typically not exposed to the outside world.

Sorry, after rereading your comment I realized that I forgot about my initial motivation behind this issue and focused on my current motivation (frontend development). I have currently addressed this need by in meantime implementing my own handler which does something similar, so I forgot about that.

So the reason why I opened this issue in the first place was in fact for this "internal" use. Our frontend obtains ID token for the user, when user signs-in, and then we pass that ID token in `Authorization` header to the server and API there. We use [Kong](https://konghq.com/) then to validate the ID token and map it to simpler HTTP header which is then used by internal services, which do not have to validate tokens anymore, but just trust what Kong decides. Now, we could do token validation inside Kong plugin (and some standard OAuth already exist), but to me it looked even simpler (if it would exist) that I would simply delegate to "standard" introspect handler to determine if provided token is same or not. In this way I do not have to worry about public keys, caching of them, and so on. I call the introspect endpoint and I know that it is the only source of truth. So I tried that and I was surprised that it did not work on ID tokens.

In addition to this use case, I think it is useful for debugging by clients/frontend, as I described above.

**Comment by mitar** [comment]
I am aware that we could also obtain access token, but ID token has some useful information (like subject) in JWT which then allows us to just map the token without additional database query.

**Comment by aeneasr** [comment]
I thought about this more and I think this is very dangerous. An ID Token is fundamentally different from an access token. The former can not be revoked while the latter can (in real time). The former is proof of authentication, the latter proof of authorization. The introspection spec does not return the concrete token type (only `Bearer`) and must check all registered strategies (e.g. first check access token, then refresh token, then id token) which could lead an authorization server wrongfully accepting an ID Token as proof of authorization.

This is already problematic for `refresh_token`s as they could theoretically be used as long living credentials and I think the RFC does not explain what needs to be done here.

**Comment by mitar** [comment]
> The former can not be revoked while the latter can (in real time).

Unless the latter is JWT as well and use use stateless introspection. Which we do support. (With a big warning.)

> which could lead an authorization server wrongfully accepting an ID Token as proof of authorization.

I think this just shows that if you are using introspection endpoint to validate tokens (to check if they should be accepted) then you should also pass `audience` parameter to check that the given token is for expected audience. This solves the problem of one using access token meant for one audience to gain access to another audience (both tokens are valid, just audience is different). And same holds for ID tokens and access tokens. If you worry you could confuse them (you use introspection endpoint to validate tokens to determine access) then you should pass `audience` parameter.

So my proposal would be:
* We should add `audience` parameter to the introspection endpoint. If somebody is using it to validate tokens to determine access, they should pass both `scope` and `audience` parameters. This is the only way to be safe.
* Thus, we can support ID token introspection.

**Comment by aeneasr** [comment]
> I think this just shows that if you are using introspection endpoint to validate tokens (to check if they should be accepted) then you should also pass audience parameter to check that the given token is for expected audience. This solves the problem of one using access token meant for one audience to gain access to another audience (both tokens are valid, just audience is different). And same holds for ID tokens and access tokens. If you worry you could confuse them (you use introspection endpoint to validate tokens to determine access) then you should pass audience parameter.

This is problematic because `aud` or `audience` is not standardised in OAuth2. It's a claim in JWT but there are actually no standards around how you would request the `audience`. Thus, imposing this requirement means that we're bending the spec. I understand the reason, but the real-world application might be difficult. What do you think?

**Comment by mitar** [comment]
Same holds for current `scope` parameter to introspect endpoint, no? That is also not by the spec? So I think the whole use of introspect endpoint to validate something beyond expiration time and correct signature seems to be out of spec?

**Comment by mitar** [comment]
(For everyone reading this, see also [this thread](https://github.com/ory/fosite/pull/519#discussion_r511577410) for initial discussion before it was moved here.)

**Comment by mitar** [comment]
So I am still interested in this, but there was no conclusion if this should be implemented. See my [proposal above](https://github.com/ory/fosite/issues/410#issuecomment-718544782).

**Comment by aeneasr** [comment]
I re-read the points and still stand by my initial comment. Introspection is very clearly defined as:

> This specification defines a method for a protected resource to query
   an OAuth 2.0 authorization server to determine the active state of an
   OAuth 2.0 token and to determine meta-information about this token.
   OAuth 2.0 deployments can use this method to convey information about
   the authorization context of the token from the authorization server
   to the protected resource.

That, by definition, excludes ID Tokens for the already mentioned issues. I think the userinfo endpoint might be able to handle this iirc.

**Comment by aeneasr** [comment]
> Should I open another issue for adding audience parameter to introspection endpoint (for access tokens).

or even a PR! :)

> Google has tokeninfo endpoint which to me looks like introspection endpoint and it accepts ID token

I think Google's approach makes sense as that endpoint is there solely for ID Token introspection! I looked through the specs because It hought `/userinfo` surely had an ID token introspection mechanism, but apparently not so! IMO that endpoint would be best suited for this though...

**Comment by mitar** [comment]
BTW, OpenID Connect working group aligns with your perspective: https://bitbucket.org/openid/connect/issues/1350/support-for-id-tokens-in-introspection

**Comment by aeneasr** [comment]
Thank you for following up!

**Comment by mitar** [comment]
This is a good point. I think we discussed this a few times. Does fosite now adds `typ` to headers of JWT tokens it issues? If not, maybe we should open an additional issue for it to start doing that.

**Comment by james-d-elliott** [comment]
I have a feeling I made this change and it was merged, or I at least PR'd it, but I'd suggest double checking to be sure. A search for `at+jwt` would probably reveal a lot.

**Comment by mitar** [comment]
I see #737, but I do not see if introspection endpoint then enforces this in any way? It looks to me like it would still accept a state-less JWT ID token?

**Comment by james-d-elliott** [comment]
Unmerged: https://github.com/ory/fosite/pull/767/files

**Comment by mitar** [comment]
Oh, I completely forgot about that. Awesome work there. It should really be merged in. @aeneasr?
