### ISSUE TITLE
History file is out of date

### ISSUE THREAD

**Issue by mitar** [ory/fosite#414]
[History file](https://github.com/ory/fosite/blob/master/HISTORY.md) seems very out of date (latest version 0.28.0) in comparison with [releases](https://github.com/ory/fosite/releases) (latest version 0.31.0).

Moreover, [releases](https://github.com/ory/fosite/releases) have bad rendering because of too long lines sometimes.

Also, consider using [Keep a changelog](https://keepachangelog.com/en/1.0.0/) format for the changelog. It is pretty popular these days and allows tools to parse it. This is important especially for security-focused projects because it allows one to have automatic notifications about when should dependencies in a project using this library be updated (for example, if you push an important security fix).

BTW, have you considered adding this package into [Tidelift](https://tidelift.com/) (I see you use only Patreon and OpenCollective for sponsorship). They work with maintainers to add some best practices in maintaining the package (like changelog and security disclosures) and then communicate such important updates like security updates to users of the package (and payed subscribers to their service). I think it is a pretty neat model for financing open source projects.

**Comment by aeneasr** [comment]
> History file seems very out of date (latest version 0.28.0) in comparison with releases (latest version 0.31.0).
>
> Moreover, releases have bad rendering because of too long lines sometimes.
>
> Also, consider using Keep a changelog format for the changelog. It is pretty popular these days and allows tools to parse it. This is important especially for security-focused projects because it allows one to have automatic notifications about when should dependencies in a project using this library be updated (for example, if you push an important security fix).

We're enforcing conventional commits across the repo which will hopefully improve this and let us use a changelog generator. Writing manual guides is unfortunately not possible for me due to workload.

> BTW, have you considered adding this package into Tidelift (I see you use only Patreon and OpenCollective for sponsorship). They work with maintainers to add some best practices in maintaining the package (like changelog and security disclosures) and then communicate such important updates like security updates to users of the package (and payed subscribers to their service). I think it is a pretty neat model for financing open source projects.

We gave Tidelift a look but since it primarily targets software libraries, and Dockertest/Fosite/Ladon are pretty much the only libraries we have, we're not sure if it's worth the effort. Do you have experience with running a Tidelift project?

**Comment by mitar** [comment]
> We gave Tidelift a look but since it primarily targets software libraries, and Dockertest/Fosite/Ladon are pretty much the only libraries we have, we're not sure if it's worth the effort.

Yes, I wrote to them about that as well, asking them to support also services and not just libraries. It is on their roadmap, but not yet.

I mean, the only effort is really getting the package up to speed to some best practices, including handling releases, changelog, and security disclosures. So it is not a lot of extra effort for Tidelife itself (just add one sponsorship GitHub file and add a section to README telling that people can get enterprise support at Tidelift). But yes, following those best practices is probably a bit more effort than I currently see here. ;-) But also just initially, I think. Once you get processes in place it should not bee too much extra effort.

> Do you have experience with running a Tidelift project?

Yes, but a very low key, without any income from it.  So I do not think I can provide any realistic insight here.

**Comment by aeneasr** [comment]
Except for the changelog, which is just a small automation step in the CI, we already follow all other conventions. So yes, adding it to Tidelift probably isn't a lot of work!

**Comment by mitar** [comment]
So any plans on making changelog better? Or just remove it and direct users to GitHub releases? Or build the changelog from GitHub releases?

**Comment by aeneasr** [comment]
We've adopted convential commits in other repositories and it works very well! Here's an example: https://github.com/ory/kratos/blob/master/CHANGELOG.md#breaking-changes

I would favor using that as it reduces the work for maintainers :)

**Comment by mitar** [comment]
Yes, that looks pretty neat. My only minus is that it does not like to PRs but to commits. But yes, anything is better than what is currently in this repository. :-)

**Comment by aeneasr** [comment]
Haha yeah :) For PRs we usually squash & merge and modify the commit message, which should basically do what you want, right?

**Comment by mitar** [comment]
No. I mean that in the changelog, there is no link to the GitHub PR which made that squashed commit. So it is hard to see all the discussion and rationale which made that commit. But you can at least click the commit and generally there is a PR link in the commit message there. So it is OK. But not as nice as it could be. :-)

**Comment by aeneasr** [comment]
Ah right I see - I don't think the changelog generator is capable of that :/

**Comment by mitar** [comment]
Hm, https://github.com/ory/fosite/blob/master/HISTORY.md is still out of date?

**Comment by aeneasr** [comment]
Right, I'll add a note that the doc is deprecated and that one should look here instead: https://github.com/ory/fosite/blob/master/CHANGELOG.md

**Comment by mitar** [comment]
Just remove that file?

**Comment by mitar** [comment]
Or link to its historic content at the last commit where it exists from HISTORY.md?
