### ISSUE TITLE
A configuration option to make audience required

### ISSUE THREAD

**Issue by mitar** [ory/fosite#416]
**Is your feature request related to a problem? Please describe.**

Currently it looks like even if I list audiences for a client in the configuration, `DefaultAudienceMatchingStrategy` does not force any audience to be requested. I think it would be a more secure configuration, if I could require at least one of audiences to be requested.

**Describe the solution you'd like**

Add `EnforceAudience bool` to `Config` which would require at least one audience to be requested. Then existing `DefaultAudienceMatchingStrategy` would validate that it is among allowed ones.

**Describe alternatives you've considered**

I could create a custom audience matching strategy, but to me it seems this something worth being in Fosite core.

**Comment by aeneasr** [comment]
Since the audience isn't even properly standardized, I'm not sure if enforcing it is the best path forward?

**Comment by mitar** [comment]
What do you mean it is not properly standardized?

**Comment by aeneasr** [comment]
The `aud` claim is something that's specified in the JSON Web Token spec. It's not something that comes from any OAuth2 or OpenID Connect spec. It has become a de-facto standard because it's being used across Google but everyone requests the audience a little different (is it a string? an array of strings? what's the parameter name? when do I send it?).

There's [one attempt](https://tools.ietf.org/id/draft-tschofenig-oauth-audience-00.html
) at standardizing this that I know of but I don't think it got anywhere (expired 2013).

**Comment by mitar** [comment]
Hm, I see in [spec here](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) that it describes audience:

> REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

Am I confusing something here?

**Comment by aeneasr** [comment]
> Am I confusing something here?

Yes, that is the ID Token which follows the JSON Web Token spec which requires the audience claim to be present. There is no mention of how that is specified (a) for access tokens (b) for refresh tokens and neither does the spec mention how a RP may request an audience for any token type.

**Comment by mitar** [comment]
OK, but if Fosite does allow multiple audience values for ID tokens, and client can choose from them, and it even has extensible code how to match audience values, then I think it is still a valid request to decide how to handle empty lists of audience, not that all those features get into the effect only when client decides to use one. Maybe the server wants to require that at least one is selected? I mean, it makes the featureset complete here.

**Comment by mitar** [comment]
I added this myself in my handlers, so after validating audiences I check how many are there.
