### ISSUE TITLE
A conformance test suite for storage

### ISSUE THREAD

**Issue by mitar** [ory/fosite#421]
**Is your feature request related to a problem? Please describe.**

Given that [secure storage](https://grokbase.com/t/gg/golang-nuts/15cz98x0t1/go-nuts-help-me-build-a-security-first-oauth2-ehlper-library-for-golang) is/was one of the goals of this project, and that this project does not provide a persistent storage implementation, one has to implement storage themselves. But it is hard to know if implementation is correct.

**Describe the solution you'd like**

A test suite one can run against a storage implementation to determine (to some degree of certainty) that storage implementation behaves correctly.

**Additional context**

Given the lack of documentation on storage, such test suite could also help explain expected behavior of implementation to a human reader.

**Comment by aeneasr** [comment]
Good idea! This will need to cover lots of bases though because many flows are dependent on one another when it comes to consistency (e.g. access and refresh tokens). I think that a better approach would be e2e conformance tests that can use an interchangable storage implementation.

**Comment by mitar** [comment]
Yes, I was also thinking that probably e2e conformance tests for this whole package could be (re)used. Are current unit tests for this package close to that?

**Comment by aeneasr** [comment]
No, the unit tests use a lot of mocking. Hydra has most of these conformance tests. Best idea would probably to use the official OIDC conformance suite. It's quite buggy though (especially when receiving unexpected results) and I have never set it up in a CI. I believe this is the project (looks like they moved to gitlab): https://gitlab.com/openid/conformance-suite

**Comment by aeneasr** [comment]
Here's some docs how Keycloak runs this suite: https://github.com/keycloak/keycloak/blob/master/docs/tests-oidc-conformance.md

**Comment by mitar** [comment]
Oh, you are right. That would be probably good, to have CI for this whole project to continue to test for conformance. And then the same thing could be maybe reused to check if with new storage you still pass.

**Comment by aeneasr** [comment]
Yes, I think that would be the idea! There's still a lot of implementation details in the actual consumption of this library (fosite-example) that we might want to abstract away in the library but I think by moving some of the pieces (such as discovery documents) to fosite we already win in some areas.

**Comment by matthewhartstonge** [comment]
So tell me about the fosite integration tests...

I was looking at them tonight, as I'm looking to update my fosite mongo driver. It feels like opening the integration tests up to enable dependency injection could be a good first step?

**Comment by aeneasr** [comment]
I really want to discourage you to use a document store for solving a relational problem which is fosite. Without proper foreign keys and indices for joins you will end up having a very hard time running this at scale.

**Comment by mitar** [comment]
> I really want to discourage you to use a document store for solving a relational problem which is fosite. Without proper foreign keys and indices for joins you will end up having a very hard time running this at scale and maintaining its security.

I do not get why would this be the case? To me it looks like Fosite data storage is very non-relational. You mostly need one document per client configuration and one document per requester, which has then sub-fields for various tokens so that you can query that up. So two collections and not really any joins. Am I missing something?

**Comment by aeneasr** [comment]
> You mostly need one document per client configuration and one document per requester, which has then sub-fields for various tokens so that you can query that up.

Missing: Token revokation on client deletion, keeping check of token chains, who consented to what, revoking that consent, ...

> Am I missing something?

Yes, a ton (see above). Look at Hydra's data model and you'll understand why.

Just the mere fact that eventual consistency will lead to duplicate token issuance (we had these issues with relational stores but were able to solve them with different TX levels) in high traffic environments should scare you off enough.

And if that's not enough, trust the guy who wrote this stuff back in 2016 with a document store (I forgot the name...) and eventually had to realize that it's the wrong technology. He also has been maintaining and rewriting one of the most popular oauth2 servers around since then ;)

**Comment by mitar** [comment]
> Token revokation on client deletion, keeping check of token chains, who consented to what, revoking that consent, ...

I do not see why that would be tricky? You delete client document from clients collection. You delete/mark all tokens for that client revoked in tokens collection. Why you need joins here?

> Just the mere fact that eventual consistency will lead to duplicate token issuance

Ehm, MongoDB has unique indices and upserts and other similar stuff which can help here?

> eventual consistency

MongoDB does not have eventual consistency? Also, it has [transactions](https://docs.mongodb.com/manual/core/transactions/) now, if you really want them. Even joins. It really went a whole circle here. :-) But it allows much richer data model than SQL, with embedded objects and lists, which makes a lot of things much simpler and easier. PostgreSQL also supports composite types, but it is not really possible to [parse them automatically from query results](https://github.com/brianc/node-postgres/issues/1801).

**Comment by mitar** [comment]
In any case, my interest here is to implement a [gorm storage backend](https://jinzhu.me/gorm/) and not really MongoDB. But I do struggle a bit currently understanding the data model required by Fosite, so #420 or better documentation/entity diagram would be awesome to have.

**Comment by aeneasr** [comment]
I'm not going to go into an argument over datastores. I was also not explicitly targeting MongoDB which supports eventual consistency for replica sets, but rather document stores in general. You can take advice from the author/maintainer of a library you use or leave it - it's up to you! I just want to save you time and frustration, because I want you to avoid the mistakes I made with this stuff.

**Comment by mitar** [comment]
Thanks, and I appreciate this. I think what I am missing here is some documentation/record of those pitfalls, so it would be possible for me (and others) to understand what all to think about when implement a storage backend. So to share those lessons learned in a way that somebody else can learn from them as well. This is why I was asking for more details and arguing, to better understand what exactly are failure modes here. Just saying "MongoDB does not work for fosite" does not allow me to understand if some of failure modes might be present also in my own storage backend.

**Comment by aeneasr** [comment]
I would love to document that but I'm simply lacking time - it's also an accumulation of things that happened over the lifespan of the projects. Primary issues are FK triggers for when something is deleted (access token -> refresh token, refresh token -> all access tokens, authorize code -> refresh + access tokens, oauth2 clients -> everything, user consent -> tokens, ... (many more cases in a properly implemented project)), JOINs to make sense of who allowed what when where, and so on.

Keep in mind that OAuth2 is not just tokens and clients, but also user consent, auth sessions, permissions remembered, permissions revoked, consent revoked, and so on. That's why I always encourage people to use ORY Hydra instead of doing this on their own - there's a lot of complexity not covered by Fosite itself.

The best docs you'll find on this is probably ORY Hydra's data model!

**Comment by mitar** [comment]
I found that Hydra if fact provides something a test suite one can [use](https://github.com/ory/hydra/blob/24f91ab7038e4c612db5af86ff0f3ee5eb03c878/oauth2/fosite_store_helpers.go#L152-L182). So maybe we should move that to fosite?

**Comment by aeneasr** [comment]
This is actually already the case - however we do conformance testing with Hydra that uses the current fosite version. From our end there is little appetite to write a completely new test suite for fosite standalone as implementing all the details is hell - and we would end up writing lots of code again that exists in Hydra. Therefore closing this as we have conformance testing in place now, even if it’s not standalone!

**Comment by mitar** [comment]
I mean, this issue if for fosite. I think it would be useful to have it here, so those who do want to use fosite could run that test suite and have higher chance of knowing if things work correctly. I think we could just copy things here, if you think making it general would not work for hydra (not sure why, it looks like it is pretty general already)?

So not sure why closing this. This is for fosite and in fosite there is no such conformance testing.

**Comment by aeneasr** [comment]
We can reopen it but as stated above:

- We have a conformance suite for fosite (requires integration with Hydra however)
- Writing a conformance suite for fosite would require a SQL storage system or a storage system which respects foreign keys, several management functions around scopes, claims, and more:
  - cryptographic key management
  - several endpoints for e.g. dynamic client registration
  - probably 10 other things I forgot

All of this would take myself at least 3 months of work (if not more) and I suspect it will take non-maintainers much longer. Personally, I have no time to work on this and from experience I suspect that no community member will work on this due to the complexity, or if they do, for their integration. Therefore the issue was closed as kind-of-implemented/wontfix. We can keep it open but who realistically will work on this?

**Comment by mitar** [comment]
I looked again at the code of the test suite in Hydra and I see that it is tightly integrated with Hydra. It looked to me like it is more abstract. Thus I do agree with your conclusion for this issue. Thank you for the explanation.

**Comment by mitar** [comment]
I looked into this again and I found out that it is possible to do it and I have done it. It was a day of work. I have done it for my `GormStore`. So maybe we do not talk about the same thing. I am talking about a test suite for Fosite storage only, so not sure where does key management and dynamic client registration come into play, that is not part of Fosite. I would like something which exercises [CoreStorage](https://github.com/ory/fosite/blob/master/handler/oauth2/storage.go#L30) interface and [Transactional](https://github.com/ory/fosite/blob/master/storage/transactional.go) interface and so on. Call them and see that they are returning correct things.

There is already a test suite of tests in [Hydra](https://github.com/ory/hydra/blob/24f91ab7038e4c612db5af86ff0f3ee5eb03c878/oauth2/fosite_store_helpers.go#L152-L182) which seems to be doing this. With a bit of wrapping code one can get it to run as a test case for Fosite storage itself. To make this work I have defined the following in-memory structures:

```golang
// ClientManager is an in-memory implementation of client.Manager.
// Not all methods are implemented (focus is on those which
// are needed for Hydra test suite for storage).
type ClientManager struct {
	Clients map[string]*client.Client

	clientsMutex sync.RWMutex
}

func (c *ClientManager) GetClient(ctx context.Context, id string) (fosite.Client, error) {
	return c.GetConcreteClient(ctx, id)
}

func (c *ClientManager) CreateClient(ctx context.Context, cl *client.Client) error {
	c.clientsMutex.Lock()
	defer c.clientsMutex.Unlock()

	c.Clients[cl.OutfacingID] = cl
	return nil
}

func (c *ClientManager) UpdateClient(ctx context.Context, cl *client.Client) error {
	c.clientsMutex.Lock()
	defer c.clientsMutex.Unlock()

	c.Clients[cl.OutfacingID] = cl
	return nil
}

func (c *ClientManager) DeleteClient(ctx context.Context, id string) error {
	c.clientsMutex.Lock()
	defer c.clientsMutex.Unlock()

	delete(c.Clients, id)
	return nil
}

func (c *ClientManager) GetClients(ctx context.Context, filters client.Filter) ([]client.Client, error) {
	c.clientsMutex.Lock()
	defer c.clientsMutex.Unlock()

	clients := []client.Client{}
	i := -1
	for _, cl := range c.Clients {
		if filters.Name != "" && cl.Name != filters.Name {
			continue
		}

		if filters.Owner != "" && cl.Owner != filters.Owner {
			continue
		}

		i += 1
		if i < filters.Offset {
			continue
		}

		clients = append(clients, *cl)

		limit := filters.Limit
		if limit <= 0 || limit > 500 {
			limit = 500
		}
		if len(clients) >= limit {
			break
		}
	}
	return clients, nil
}

func (c *ClientManager) CountClients(ctx context.Context) (int, error) {
	c.clientsMutex.Lock()
	defer c.clientsMutex.Unlock()

	return len(c.Clients), nil
}

func (c *ClientManager) GetConcreteClient(ctx context.Context, id string) (*client.Client, error) {
	c.clientsMutex.Lock()
	defer c.clientsMutex.Unlock()

	cl, ok := c.Clients[id]
	if !ok {
		return nil, fosite.ErrNotFound
	}
	return cl, nil
}

func (c *ClientManager) Authenticate(ctx context.Context, id string, secret []byte) (*client.Client, error) {
	panic("not implemented")
}

// ConsentManager is an in-memory implementation of consent.Manager.
// Not all methods are implemented (focus is on those which
// are needed for Hydra test suite for storage).
type ConsentManager struct {
	ConsentRequests map[string]*consent.ConsentRequest
	LoginSessions   map[string]*consent.LoginSession
	LoginRequests   map[string]*consent.LoginRequest
	LogoutRequests  map[string]*consent.LogoutRequest

	consentRequestsMutex sync.RWMutex
	loginSessionsMutex   sync.RWMutex
	loginRequestsMutex   sync.RWMutex
	logoutRequestsMutex  sync.RWMutex
}

func (c *ConsentManager) CreateConsentRequest(ctx context.Context, req *consent.ConsentRequest) error {
	c.consentRequestsMutex.Lock()
	defer c.consentRequestsMutex.Unlock()

	c.ConsentRequests[req.ID] = req
	return nil
}

func (c *ConsentManager) GetConsentRequest(ctx context.Context, challenge string) (*consent.ConsentRequest, error) {
	c.consentRequestsMutex.Lock()
	defer c.consentRequestsMutex.Unlock()

	req, ok := c.ConsentRequests[challenge]
	if !ok {
		return nil, fosite.ErrNotFound
	}
	return req, nil
}

func (c *ConsentManager) HandleConsentRequest(ctx context.Context, challenge string, r *consent.HandledConsentRequest) (*consent.ConsentRequest, error) {
	// This is not really doing any handling of the consent request. It just pretends
	// it has done it and returns the consent request.
	return c.GetConsentRequest(ctx, challenge)
}

func (c *ConsentManager) RevokeSubjectConsentSession(ctx context.Context, user string) error {
	panic("not implemented")
}

func (c *ConsentManager) RevokeSubjectClientConsentSession(ctx context.Context, user string, client string) error {
	panic("not implemented")
}

func (c *ConsentManager) VerifyAndInvalidateConsentRequest(ctx context.Context, verifier string) (*consent.HandledConsentRequest, error) {
	panic("not implemented")
}

func (c *ConsentManager) FindGrantedAndRememberedConsentRequests(ctx context.Context, client string, user string) ([]consent.HandledConsentRequest, error) {
	panic("not implemented")
}

func (c *ConsentManager) FindSubjectsGrantedConsentRequests(ctx context.Context, user string, limit int, offset int) ([]consent.HandledConsentRequest, error) {
	panic("not implemented")
}

func (c *ConsentManager) CountSubjectsGrantedConsentRequests(ctx context.Context, user string) (int, error) {
	panic("not implemented")
}

func (c *ConsentManager) GetRememberedLoginSession(ctx context.Context, id string) (*consent.LoginSession, error) {
	c.loginSessionsMutex.Lock()
	defer c.loginSessionsMutex.Unlock()

	req, ok := c.LoginSessions[id]
	if !ok {
		return nil, fosite.ErrNotFound
	}
	return req, nil
}

func (c *ConsentManager) CreateLoginSession(ctx context.Context, session *consent.LoginSession) error {
	c.loginSessionsMutex.Lock()
	defer c.loginSessionsMutex.Unlock()

	c.LoginSessions[session.ID] = session
	return nil
}

func (c *ConsentManager) DeleteLoginSession(ctx context.Context, id string) error {
	c.loginSessionsMutex.Lock()
	defer c.loginSessionsMutex.Unlock()

	delete(c.LoginSessions, id)
	return nil
}

func (c *ConsentManager) RevokeSubjectLoginSession(ctx context.Context, user string) error {
	panic("not implemented")
}

func (c *ConsentManager) ConfirmLoginSession(ctx context.Context, id string, authTime time.Time, subject string, remember bool) error {
	panic("not implemented")
}

func (c *ConsentManager) CreateLoginRequest(ctx context.Context, req *consent.LoginRequest) error {
	c.loginRequestsMutex.Lock()
	defer c.loginRequestsMutex.Unlock()

	c.LoginRequests[req.ID] = req
	return nil
}

func (c *ConsentManager) GetLoginRequest(ctx context.Context, challenge string) (*consent.LoginRequest, error) {
	c.loginRequestsMutex.Lock()
	defer c.loginRequestsMutex.Unlock()

	req, ok := c.LoginRequests[challenge]
	if !ok {
		return nil, fosite.ErrNotFound
	}
	return req, nil
}

func (c *ConsentManager) HandleLoginRequest(ctx context.Context, challenge string, r *consent.HandledLoginRequest) (*consent.LoginRequest, error) {
	c.loginRequestsMutex.Lock()
	defer c.loginRequestsMutex.Unlock()

	return c.GetLoginRequest(ctx, challenge)
}

func (c *ConsentManager) VerifyAndInvalidateLoginRequest(ctx context.Context, verifier string) (*consent.HandledLoginRequest, error) {
	panic("not implemented")
}

func (c *ConsentManager) CreateForcedObfuscatedLoginSession(ctx context.Context, session *consent.ForcedObfuscatedLoginSession) error {
	panic("not implemented")
}

func (c *ConsentManager) GetForcedObfuscatedLoginSession(ctx context.Context, client string, obfuscated string) (*consent.ForcedObfuscatedLoginSession, error) {
	panic("not implemented")
}

func (c *ConsentManager) ListUserAuthenticatedClientsWithFrontChannelLogout(ctx context.Context, subject string, sid string) ([]client.Client, error) {
	panic("not implemented")
}

func (c *ConsentManager) ListUserAuthenticatedClientsWithBackChannelLogout(ctx context.Context, subject string, sid string) ([]client.Client, error) {
	panic("not implemented")
}

func (c *ConsentManager) CreateLogoutRequest(ctx context.Context, request *consent.LogoutRequest) error {
	c.logoutRequestsMutex.Lock()
	defer c.logoutRequestsMutex.Unlock()

	c.LogoutRequests[request.ID] = request
	return nil
}

func (c *ConsentManager) GetLogoutRequest(ctx context.Context, challenge string) (*consent.LogoutRequest, error) {
	c.logoutRequestsMutex.Lock()
	defer c.logoutRequestsMutex.Unlock()

	request, ok := c.LogoutRequests[challenge]
	if !ok {
		return nil, fosite.ErrNotFound
	}
	return request, nil
}

func (c *ConsentManager) AcceptLogoutRequest(ctx context.Context, challenge string) (*consent.LogoutRequest, error) {
	panic("not implemented")
}

func (c *ConsentManager) RejectLogoutRequest(ctx context.Context, challenge string) error {
	panic("not implemented")
}

func (c *ConsentManager) VerifyAndInvalidateLogoutRequest(ctx context.Context, verifier string) (*consent.LogoutRequest, error) {
	panic("not implemented")
}

// Registry is an in-memory implementation of InternalRegistry.
// Registry is at the same time x.FositeStorer and many methods
// it delegates to embedded GormStore.
// Not all methods are implemented (focus is on those which
// are needed for Hydra test suite for storage).
type Registry struct {
	*store.GormStore
	clientManager  *ClientManager
	consentManager *ConsentManager
}

func (r *Registry) ClientValidator() *client.Validator {
	panic("not implemented")
}

func (r *Registry) ClientManager() client.Manager {
	return r.clientManager
}

func (r *Registry) ClientHasher() fosite.Hasher {
	panic("not implemented")
}

func (r *Registry) Writer() herodot.Writer {
	panic("not implemented")
}

func (r *Registry) Logger() *logrusx.Logger {
	panic("not implemented")
}

func (r *Registry) AuditLogger() *logrusx.Logger {
	panic("not implemented")
}

func (r *Registry) ConsentManager() consent.Manager {
	return r.consentManager
}

func (r *Registry) ConsentStrategy() consent.Strategy {
	panic("not implemented")
}

func (r *Registry) SubjectIdentifierAlgorithm() map[string]consent.SubjectIdentifierAlgorithm {
	panic("not implemented")
}

func (r *Registry) OAuth2Storage() x.FositeStorer {
	return r
}

func (r *Registry) OAuth2Provider() fosite.OAuth2Provider {
	panic("not implemented")
}

func (r *Registry) AudienceStrategy() fosite.AudienceMatchingStrategy {
	panic("not implemented")
}

func (r *Registry) ScopeStrategy() fosite.ScopeStrategy {
	panic("not implemented")
}

func (r *Registry) AccessTokenJWTStrategy() jwk.JWTStrategy {
	panic("not implemented")
}

func (r *Registry) OpenIDJWTStrategy() jwk.JWTStrategy {
	panic("not implemented")
}

func (r *Registry) OpenIDConnectRequestValidator() *openid.OpenIDConnectRequestValidator {
	panic("not implemented")
}

func (r *Registry) AccessRequestHooks() []oauth2.AccessRequestHook {
	panic("not implemented")
}
```

Furthermore, in my `GormStore` I had to implement the following methods, additionally (to all other storage interfaces Fosite uses):

* `DeleteAccessTokens`
* `FlushInactiveAccessTokens`
* `FlushInactiveLoginConsentRequests`
* `FlushInactiveRefreshTokens`
* `GetClientAssertionJWT`
* `SetClientAssertionJWTRaw`

After all that, I can run tests:

```golang
	r := &Registry{
                GormStore: store.NewGormStore(),
		clientManager: &ClientManager{
			Clients: map[string]*client.Client{},
		},
		consentManager: &ConsentManager{
			ConsentRequests: map[string]*consent.ConsentRequest{},
			LoginSessions:   map[string]*consent.LoginSession{},
			LoginRequests:   map[string]*consent.LoginRequest{},
			LogoutRequests:  map[string]*consent.LogoutRequest{},
		},
	}

	// We do not want to specify "memory" here so that we also test transactions.
	oauth2.TestHelperRunner(t, r, "sqlite")
```

**Comment by aeneasr** [comment]
Nice, that looks cool :) It would be an option to move (part of) Ory Hydra's storage tests to Fosite and reuse them in Hydra. What do you think?

**Comment by mitar** [comment]
Yes, I think that would be great and I think it would address this issue nicely (and help anyone else writing a store for fosite).

I personally do not have time to do this at this time, though.
