### ISSUE TITLE
Add ES256 token strategy

### ISSUE THREAD

**Issue by mitar** [ory/fosite#429]
**Is your feature request related to a problem? Please describe.**

Based on [rfc7518](https://tools.ietf.org/html/rfc7518), `ES256` is in fact `Recommended+` while `RS256` is "just" `Recommended`. The `+` there means that:

> The use of "+" in the Implementation Requirements column indicates that the requirement strength is likely to be increased in a future version of the specification.

So I think it would be useful to support out of the box the "more" recommended algorithm as well. Especially if in the future it becomes required.

**Describe the solution you'd like**

An out of the box available ES256 token strategy.

**Describe alternatives you've considered**

Given how well Fosite is implemented it is easy to implement this strategy locally. But I think wider community would benefit from having best practices directly available.

**Comment by aeneasr** [comment]
Yup sounds good! Contributions welcomed :) Also, check out the PR I made against jose which hopefully helps us import their super useful generator functions: https://github.com/square/go-jose/pull/300
