### ISSUE TITLE
Support for adding additional fields to introspection result

### ISSUE THREAD

**Issue by mitar** [ory/fosite#441]
**Is your feature request related to a problem? Please describe.**

So with JWT access token strategy I can add additional custom claims. Similarly, I can add additional custom claims to ID tokens. But if I use HMAC access tokens, it seems the logical way would be that access token is opaque, but then one can use introspection endpoint to access/obtain those additional custom claims. It seems this is not possible.

**Describe the solution you'd like**

Maybe custom claims from the session should be added to the introspection output?

**Comment by aeneasr** [comment]
So we do this in Hydra and I think it makes sense to have it natively in Fosite as well!
