### ISSUE TITLE
Revocation of JWT access tokens

### ISSUE THREAD

**Issue by mitar** [ory/fosite#442]
**Is your feature request related to a problem? Please describe.**

So currently revocation of JWT access tokens is not supported by fosite. But this does not seem to be really the best practice, because some form of revocation is still possible:

* When JWT access token is revoked, it could be added to the blacklist, which then `introspect` could consult and return `false` for `active`.
* Moreover, when JWT access token is revoked, associated refresh token should be revoked, so that it is not possible to refresh those revoked JWT access tokens. This combined with short lived JWT access tokens can be pretty close to regular revocation.

**Additional context**

This is also described [in this document](https://www.oauth.com/oauth2-servers/listing-authorizations/revoking-access/).

I am not sure if for regular access tokens associated refresh tokens are revoked when the access token is revoked?

**Comment by aeneasr** [comment]
> I am not sure if for regular access tokens associated refresh tokens are revoked when the access token is revoked?

Should be the case! If not, should be fixed :)

Access token JWTs are generally not revokable because using a blacklist almost completely defeats the purpose of using a JWT, which is pass-by-value and not pass-by-reference.

**Comment by mitar** [comment]
> Access token JWTs are generally not revokable because using a blacklist almost completely defeats the purpose of using a JWT, which is pass-by-value and not pass-by-reference.

Not really. Because JWTs can contain custom claims, it can be served both for static payload of extra data about the user so that you do not have to query the database, but for validation you can still do so. But how you do then validation user of fosite can decide (call `introspect` and check if it is revoked or just validate locally). But fosite could provide revocation handler here, with a note (similarly worded like it is now, that revocation does not revoke JWT tokens unless validation against the server is done).

*But still*, revocation makes sense because it revokes refresh tokens. At least for that we should provide revocation handler for JWTs.

**Comment by aeneasr** [comment]
Yup makes sense! Keep in mind that our default JWT implementation in Hydra issues JWTs only for access tokens, not refresh tokens and I also think it supports recovation, so we might just copy that in here and adjust it a bit to make it more generic?

**Comment by mitar** [comment]
I am realizing that this is already done. So, I can use JWT tokens together with `OAuth2TokenRevocationFactory` and `OAuth2TokenIntrospectionFactory`. In this case I get revocation of JWT tokens (in a way that if you call introspection you get response that it is not active token anymore) as I am describing above: a blacklist of revoked tokens.

Or I use `OAuth2StatelessJWTIntrospectionFactory` and then I do get introspection matching how JWT validation works for the client (so no state), but there is of course then no revocation as well.

The problem is that `OAuth2StatelessJWTIntrospectionFactory` does not really work, but that is a separate issue, #445.
