### ISSUE TITLE
Make error_hint be part of error_description

### ISSUE THREAD

**Issue by mitar** [ory/fosite#456]
`error_hint` is a non-standard field being returned by fosite. Because it is not standard, standard clients do not expose it at all to developers using our system have hard time understanding what they have to change to fix the error. [RFC6749 says](https://tools.ietf.org/html/rfc6749):

> OPTIONAL.  Human-readable ASCII [USASCII] text providing additional information, used to assist the client developer in understanding the error that occurred.

I think this is exactly what `error_hint` currently is. It seems `error_description` is currently simply a standard description of the `error_code`, but it makes no sense that it is such: anyone can map `error_code` to error descriptions, ideally in the target language. On other hand, `error_description` is not meant to be shown to the user, but to the developer. So English is good there.

Similar is [written here](https://www.oauth.com/oauth2-servers/server-side-apps/possible-errors/):

> Despite the fact that servers return an error_description key, the error description is not intended to be displayed to the user. Instead, you should present the user with your own error message. This allows you to tell the user an appropriate action to take to correct the problem, and also gives you a chance to localize the error messages if you’re building a multi-language website.

So, `error_description` is for developers, `error_code` is for end-users (to be mapped to error message by the client).

So, my proposal would be that when responding, fosite would return in `error_description` what is currently `error_description` and `error_hint` together. We could leave the code mostly as it is and only when marshaling the error we would do something like `<error_description>: <error_hint>` when there is error hint.

**Comment by aeneasr** [comment]
Yeah this makes sense! It would be important to keep the existing behavior around for a while to allow clients to migrate to the new error layout but other than that I have no problem with this.

The error description currently comes from here: https://tools.ietf.org/html/rfc6749#section-4.1.2.1

In general I think that better human readable error responses would greatly help people use this framework and strain support less as no cryptic errors like "invalid_request" without any additional detail is being sent (e.g. "you used application/json but we expected www-form")

**Comment by mitar** [comment]
> Yeah this makes sense! It would be important to keep the existing behavior around for a while to allow clients to migrate to the new error layout but other than that I have no problem with this.

So, let's keep `error_hint` around as a field, but also append it to `error_description` when `error_hint` is available, would that be OK?

What about `error_debug`, should we also append this to `error_description`, when enabled to expose it in the configuration? (And keep it as a separate field?)

> In general I think that better human readable error responses would greatly help people use this framework and strain support less as no cryptic errors like "invalid_request" without any additional detail is being sent (e.g. "you used application/json but we expected www-form")

OK, I think I can make PR to combine `error_hint` into `error_description`. Improving error messages is something you probably know better which ones should be improved, and you can then add `you used application/json but we expected www-form` to `error_hint` which will then be shown after my PR to the developer.

**Comment by aeneasr** [comment]
> So, let's keep error_hint around as a field, but also append it to error_description when error_hint is available, would that be OK?

:100:

> What about error_debug, should we also append this to error_description, when enabled to expose it in the configuration? (And keep it as a separate field?)

Yeah, I'd be open to that!

> OK, I think I can make PR to combine error_hint into error_description. Improving error messages is something you probably know better which ones should be improved, and you can then add you used application/json but we expected www-form to error_hint which will then be shown after my PR to the developer.

SGTM

**Comment by mitar** [comment]
I made https://github.com/ory/fosite/pull/460 to address this.
