### ISSUE TITLE
Support OpenID Connect RP-Initiated Logout

### ISSUE THREAD

**Issue by mitar** [ory/fosite#462]
Something similar is supported in Hydra (but not fully by the spec), but not in Fosite. I think it would be great if it would be supported in fosite so that others can take advantage of it. Otherwise one has to implement this on their own. :-(

Spec:  https://openid.net/specs/openid-connect-rpinitiated-1_0.html

Hydra implements something similar, but does not mention the spec directly https://www.ory.sh/hydra/docs/concepts/logout/

**Comment by mitar** [comment]
In fact, I am more interested in OpenID Connect RP-Initiated Logout: https://openid.net/specs/openid-connect-rpinitiated-1_0.html

In fact Hydra implements it, but does not mention it in https://www.ory.sh/hydra/docs/concepts/logout/

**Comment by mitar** [comment]
I suggest we add `LogoutEndpointHandler` with `LogoutRequester` and `LogoutResponder`. I have something like that already implemented and is pretty simple I think, if you are OK I could contribute it to the fosite. Is a bit different from Hydra because it goes by the current version of the spec.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
