### ISSUE TITLE
Support for response_mode parameter and form post response mode

### ISSUE THREAD

**Issue by mitar** [ory/fosite#470]
`response_mode` is defined here: https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

Why I find it useful is that you can then use [Form Post Response mode](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html) which I think mitigates many issues with query and fragment response modes.

So I would suggest `response_mode` is supported, together with form post response mode.

**Comment by pjcdawkins** [comment]
We use response_mode=postMessage with prompt=none for an iframe "silent refresh" flow

**Comment by aeneasr** [comment]
Contribs welcomed!

**Comment by mitar** [comment]
Is `postMessage` standardized somewhere?

**Comment by aeneasr** [comment]
So I meant contribs for `form_post`!

**Comment by mitar** [comment]
FYI, for `response_mode=postMessage ` I think you are referring to [this draft](https://tools.ietf.org/html/draft-sakimura-oauth-wmrm-00)? Sadly, it has not been standardized yet. But [auth0](https://auth0.com/docs/protocols/protocol-oauth2#authorization-endpoint) does support it as one of response modes. Maybe fosite should, too.

**Comment by aeneasr** [comment]
I don't think that we should support `postMessage`. It looks very legacy and we've never had anyone ask about this before or if they did, the flow could be solved using a much simpler method.

**Comment by mitar** [comment]
Hm, to me it looks like one which is required to go around issues with 3rd party cookies, no? I am not sure what is the difference between `response_mode=postMessage` and [assisted token flow](https://github.com/ory/fosite/issues/408). The latter looks like something modern and useful today.

**Comment by aeneasr** [comment]
Hard to say honestly, I would need to spend some good time reading all the different specs. I think for now - and unless someone asks - we'll just put it on the backburner. Since the OP requested form_post which is currently being worked on I'd probably also just close this unless @pjcdawkins chimes in as to why we would need `postMessage`

**Comment by aeneasr** [comment]
This is now implemented!
