### ISSUE TITLE
Not possible to install fosite v0.32.3

### ISSUE THREAD

**Issue by mitar** [ory/fosite#478]
**Describe the bug**

I am trying to upgrade to v0.32.2. I get an error:

```
go get: github.com/ory/fosite@v0.32.2 updating to
	github.com/ory/fosite@v0.32.3/go.mod: verifying module: github.com/ory/fosite@v0.32.3/go.mod: reading https://sum.golang.org/lookup/github.com/ory/fosite@v0.32.3: 410 Gone
	server response: not found: create zip: case-insensitive file name collision: ".github/PULL_REQUEST_TEMPLATE.md" and ".github/pull_request_template.md"
```

**To Reproduce**

* I run `go get -u ./...` in my go package which has fosite as a dependency.

**Expected behavior**

It should upgrade.

**Environment**

Ubuntu 20.04. go1.14.4.

**Comment by mitjat** [comment]
This should be resolved by https://github.com/ory/fosite/pull/474

**Comment by lagren** [comment]
Also applies to 0.32.3

**Comment by mitar** [comment]
In fact the issue is just with 0.32.3.
