### ISSUE TITLE
Do not run scheduled jobs on forks

### ISSUE THREAD

**Issue by mitar** [ory/fosite#494]
Could you add to scheduled github workflows a condition to run them only on this repository and not forks?

Something like it is described here: https://github.community/t/stop-github-actions-running-on-a-fork/17965/2

```
if: github.repository == 'ory/fosite'
```

Because now I am getting errors in my fork on a daily basis because jobs run, but do not have tokens to do their job.

**Comment by aeneasr** [comment]
Makes sense!
