### ISSUE TITLE
audience parameter splitting by space

### ISSUE THREAD

**Issue by mitar** [ory/fosite#504]
**Is your feature request related to a problem? Please describe.**

Currently multiple audience values are obtained by:

```
audience := stringsx.Splitx(request.Form.Get("audience"), " ")
```

I think audiences are generally URIs, so I find it surprising that they are simply passed as a space-delimited string. I can understand that spec is like that for `scope` and `grant_type`, but I think there is no spec for `audience` and this is a custom parameter?

The issue here is that what does one do if URI contains a query parameter with a space? I know this might not be realistic, but just makes me think. So I do not have here a real problem I encountered, except that I simply assumed I have to list multiple audiences multiple times, and not with a space in between.

**Describe the solution you'd like**

I think fosite should support also passing audience as multiple parameters. golang already parses this correctly and you can obtain an array of them through `request.Form["audience"]`. Because I think space is rare in the URI we could keep that for backwards compatibility and simply process all values for the `audience` query parameter and split them by space as well.

I also think it should be documented somewhere how you pass this parameter. I have not found it documented anywhere. And the fact that it should be space separated (and if this issue is resolved, also that you can pass it by repeating the parameter).

**Describe alternatives you've considered**

We can leave it as is, but then we should at least document it better.

**Comment by mitar** [comment]
Oh, it looks like RFC 6749 says:

>  Request and response parameters MUST NOT be included more than once.

I see [that there was errata reported about this](https://mailarchive.ietf.org/arch/browse/oauth/?gbt=1&index=r_VOd2PKxGkmTu1Mjrh9K4jonWk) but there was no conclusion yet about it, but current comments are against relaxing this just here. Although, I would claim that the arguments in those comments in fact favor having `audience` parameter be repeated, because `aud` field is a list for multiple values in JWT, and arguments like this 1:1 mapping between parameters and fields. So because `scope` is a space separated value in JWT it should be one parameter, but because `aud` is a list, I would say it should be a repeated filed.

**Comment by mitar** [comment]
So it looks like [audience is defined only by a proposed standard](https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#parameters) in [RFC 8693](https://tools.ietf.org/html/rfc8693), section 2.1. In there it says that multiple values should be multiple query parameters:

> Multiple "audience" parameters may be used to indicate that the issued token is intended to be used at the multiple audiences listed.

Contrast this with scope query parameter in that spec:

> A list of space-delimited, case-sensitive strings

**Comment by aeneasr** [comment]
There is very little information available on this. The `audience` request parameter is not standardized anywhere in the standard spec. OpenID also does not specify how that claim could be set by the client.

Unless we support RFC 8693 as an extension I assume it would go against the current spec we support but if there's a real problem with spaces in URLs we could offer this as a workaround and hint towards supporting RFC 8693 at some point.

**Comment by mitar** [comment]
So, what then. Should I make a PR which adds support for `audience` to also be passed as a query string?

And where should we document any of this?

**Comment by aeneasr** [comment]
Yeah I think we could do that. How would this look though when POSTing the audience at the e.g. /oauth2/token endpoint using form encoding? This could happen when, for example, we want to introduce audience matching in client credentials flows?

**Comment by mitar** [comment]
So query string encoding and `www-form-urlencoded` encoding would simply repeat the `audience` parameter. And multipart would simply repeat multiple parts with the same field name. But we do not really have to worry about this, all this parsing is already done by default by golang.

**Comment by aeneasr** [comment]
Yup, that's correct - I just checked that that's the case. Ok, so then let's go ahead with the proposal! :)
