### ISSUE TITLE
CONTRIBUTING.md file seems to be a template

### ISSUE THREAD

**Issue by mitar** [ory/fosite#521]
**Describe the bug**

Reading `CONTRIBUTING.md` looks like it is a template which has not been rendered. Example content:

```
Contributing to ORY {{Project}}
```

**Comment by zepatrik** [comment]
This happens in https://github.com/ory/meta/blob/master/CONTRIBUTING.md

**Comment by vinckr** [comment]
Probably the same issue as: 
https://github.com/ory/meta/issues/33

**Comment by mitar** [comment]
OK, looks like a duplicate. Closing here.
