### ISSUE TITLE
Create test to assert JTI, at_hash, code_hash for refresh flows

### ISSUE THREAD

**Issue by aeneasr** [ory/fosite#524]
**Is your feature request related to a problem? Please describe.**

See https://github.com/ory/fosite/pull/523

@mitar would you be open to tackle this?

**Comment by mitar** [comment]
I am not sure how. I would need some guideline. I could not find an existing test doing this check.

So we should have a test which would make sure that refreshed tokens do not have same JIT as the original ones.

**Comment by aeneasr** [comment]
Ok, no problem, I'll try and come up with one!

**Comment by mitar** [comment]
Have you made the fix here or have you just closed the issue?
