### ISSUE TITLE
Pass request through go context

### ISSUE THREAD

**Issue by mitar** [ory/fosite#537]
**Is your feature request related to a problem? Please describe.**

We use clients which are scoped to audience parameter (we require to be) passed to endpoints. The storage `GetClient` gets only client ID to resolve the client. We currently add audience parameter to context `ctx` and then use that (go has [`WithValue`](https://golang.org/pkg/context/#WithValue)).

**Describe the solution you'd like**

I think fosite could just automatically for all requests (and responses, once they are ready) store them on `ctx` as well. It is pretty good on passing `ctx` around, request (and response) are naturally linked to `ctx` anyway. That should be pretty simple change in all codepaths where request and responses are made, we store a pointer to them also into `ctx` under some fosite-namespaced keys.

**Describe alternatives you've considered**

We are currently passing that ourselves, but it leads to a bit of duplication code in query preprocessing.

**Additional context**

I can make a PR for this if acked.

**Comment by mitar** [comment]
@aeneasr What do you think about this?

**Comment by aeneasr** [comment]
Yup we could do that - just keep in mind that things like the body can only be read once
