### ISSUE TITLE
Expired access tokens return the wrong error type

### ISSUE THREAD

**Issue by snikch** [ory/fosite#559]
(First up, thank you so much for your work on the ORY projects, they're a godsend).

RFC 6750 requires that resource servers should respond to expired access tokens with the error code `invalid_token`.
https://tools.ietf.org/html/rfc6750#section-3.1

The OpenID spec says that the `userinfo` response should use errors as per RFC 6750.
https://openid.net/specs/openid-connect-core-1_0.html#UserInfoError

Hydra's implementation does not comply and responds to an expired access token with an error code `token_expired`.
https://github.com/ory/fosite/blob/839d00093a2ed8c590d910f113186cd96fad9185/handler/oauth2/strategy_hmacsha.go#L58

**To Reproduce**

1. Generate an access token with ORY Hydra
2. Wait until the access token is expired (or expire it via the db)
3. Attempt to access the `/userinfo` endpoint with the expired access token
4. You will receive a response with `token_expired`

**Expected behavior**

The response should return `invalid_token`.

**Environment**

- Version: master

**Comment by aeneasr** [comment]
Nice find! Would you be up for a PR? :)

**Comment by mitar** [comment]
I think this can be closed now?
