### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by narg95** [ory/fosite#566]
Hi all,

onboarding people to fosite has showed me that new comers struggle to configure and personalize it for specific purposes. 
The example app is quite good to provide a fully flagged oauth server with no much effort, also the documentation on the strategies for scopes and audiences is very good. Nevertheless it does not provide a solid explanation of first-class concepts, abstractions and extension points like flows, clients,  request/response objects (access, authorize), handlers (Token, Authorize, Revocation) and how all those pieces work together to configure a reduced/tailored RFC compliant OAuth2 server.

**Describe the solution you'd like**

I would like to see in the documentation:

- How to configure fosite to support a specific flow like ClientCredentialsFlow, AuthorizationCode, etc.  
- How to sign with asymmetric or symmetric keys
- How to provide opaque or self-contained tokens (HMAC, JWT)
- How to configure custom claims in header and body
- How to configure a Client and information about their attributes and their implications e.g. `Public`, `GrantTypes`, `Audiences`
- How to provide custom Client Authentication Methods ;)
- A list of tunning/config params with their explanation like: Token life span, Issuer, Enforce PKCE, AllowedPromptValues, TokenEntropy, etc...

and an overview of fosite key concepts/abstractions and how they play all together like:

- Handlers(Token, Introspection, Authorize, Refresh)
- Request/Response objects (Access/Authorize)
- Flows: Client Credentials, Authorization Code
- Factories
- Different Strategies: Scopes, Audiences, JWT/HMAC, Client Authentication

**Describe alternatives you've considered**

Reverse engineer Fosite by cloning the code, running the example app, looking at integration tests, navigating the source code, etc. 

**Additional context**

I do not expect a Pull Request to solve it, although that would be great! 
Instead I just want to initiate the discussion to find an strategy to improve Fosite's capabilities and extensibility documentation for new comers.
This strategy can be published to be executed incrementally with internal and also external contributions

What do you think?

**Comment by aeneasr** [comment]
Yes absolutely, fosite is definitely a bit complex and there are some implicit things that are hard to figure out - such as how we deal with sessions structs. Unfortunately I am so swamped with other work that I have very little time to work on this. But if you want to work on this I can offer as much help as I can to clarify things. There are also a couple of others here (e.g. @mitar ) that have worked quite a lot with fosite and could probably help.

**Comment by mitar** [comment]
I completely agree. It is really hard to get it. I can help also a bit, but also do not have time at the moment. What I can do is share some pieces of code how I configured things, and then if somebody makes it into a documentation, would be great.

One thing I learned about documentation through time is that you need generally four pieces of documentation:
* quick start
* an in depth guide/walkthrough
* how tos
* API reference

I think fosite mostly has only a quick start, and then you are left on your own. Maybe we could just start with some how tos for common things. Like what you described above is a good list which can go into few how tos.

I would also add on the list above implementing your own storage.

**Comment by narg95** [comment]
Hey thanks for the feedback!
@mitar how should we proceed?
should I open a WIP pull request to agree in a list of how-tos e.g in an index.md file in docs/how-tos/ folder. And then we can add each how-to in its own  how-to-*.md file and pull request? 

Once they are in a good shape  we could add a reference in the README.md file.

what do you both think?

**Comment by mitar** [comment]
I think you can just start with adding a howto or two through a PR. We can link/structure them later.
