### ISSUE TITLE
Do not require state if code_challenge is used

### ISSUE THREAD

**Issue by mitar** [ory/fosite#569]
**Describe the bug**

If PKCE is used to protect the flow against CSRF, `state` should not have to be used, too. See: https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16#section-4.7.1

**To Reproduce**

GET an authorize request with `code_challenge` query string parameter present, but no `state`.

**Expected behavior**

The flow returns the code. But in fact it returns an error:

```
The+state+is+missing+or+does+not+have+enough+characters+and+is+therefore+considered+too+weak
```

**Environment**

Fosite v0.35.1.

**Comment by aeneasr** [comment]
SGTM

**Comment by mitar** [comment]
I looked a bit into this but I am not sure how can I know in one handler (which is checking for `state`) that also a PKCE handler is enabled, too? Or more generally, how can I know at the place of checking for `state` that PKCE is used for the request/flow?

**Comment by aeneasr** [comment]
Could you please link to the relevant places in the codebase your question refers to?

**Comment by mitar** [comment]
So how can I at [this point](https://github.com/ory/fosite/blob/master/authorize_request_handler.go#L348-L351) know that also a [PKCE handler is enabled](https://github.com/ory/fosite/blob/master/handler/pkce/handler.go#L54) and that this check should be skipped?

**Comment by aeneasr** [comment]
I see, the only thing I can think of would be to check the store but that would run counter to the rest of the architecture or refactor the whole validation system. Honestly, I think this is a wontfix as the impact is minimal (not required to set a random state) and the effort is huge / risky. If you agree I’ll close

**Comment by mitar** [comment]
OK.

**Comment by NickUfer** [comment]
Just ran into this with a client I cannot control. It uses PKCE and does not send a state
