### ISSUE TITLE
Support for reusing used RT in a short time window

### ISSUE THREAD

**Issue by rickliujh** [ory/fosite#580]
**Is your feature request related to a problem? Please describe.**

We're using the fosite to provide the OAuth2 service. There is one issue that our client has. When they are using the refresh token(ed RT) to refresh to access token(ed AT), the request got processed in the server, but cause some network interruption, they missed the response. In this case, they had to ask the user to log back in, Which leads to a bad user experience. 

Have any plan for including this feature for now?

**Describe the solution you'd like**

Therefore, we consider having a short time window to reusing the old RT when the client missed the response.
Then,
1. Having a toggle to choosing if enable the feature.
2. The time window of reuse RT can be configurable.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by aeneasr** [comment]
See also discussion at https://github.com/ory/hydra/issues/1831

Short answer: we'd like to support that (optionally) but it's quite complicated to implement. If you want to contribute this change we'd be happy to help where we can!

**Comment by liujh2010** [comment]
> See also discussion at [ory/hydra#1831](https://github.com/ory/hydra/issues/1831)
> 
> Short answer: we'd like to support that (optionally) but it's quite complicated to implement. If you want to contribute this change we'd be happy to help where we can!

I'm glad to do that. This feature is in our scrum plan actually, we have an internal RFC for this one so far. Would you want to review it? And where should I put it normally?

**Comment by aeneasr** [comment]
Yes, a RFC sounds great! Sorry for the late reply!

**Comment by liujh2010** [comment]
Never mind, the RFC is for our internal service, I'll take some time to adapt to fosite. And one question: where should I put RFC when it was done?

**Comment by aeneasr** [comment]
Probably best as a new issue or here :)

**Comment by liujh2010** [comment]
Sure thing, I'm working on it.

**Comment by rickliujh** [comment]
Sorry, I was too busy this year. I will take the time to try if I can finish it in our New year Vacation
