### ISSUE TITLE
Move userinfo handler from Hydra to fosite

### ISSUE THREAD

**Issue by mitar** [ory/fosite#581]
**Is your feature request related to a problem? Please describe.**

I think userinfo handler should be part of fosite and not Hydra. I am looking at [UserinfoHandler](https://github.com/ory/hydra/blob/40b09cdf69ad5cdb27c35493e345fbf9b97a7b1b/oauth2/handler.go#L278) and I literally do not see anything Hydra specific. On the other hand, this would allow fosite users to roll out one more standard oauth endpoint.

**Comment by aeneasr** [comment]
The userinfo endpoint can contain any information (from db, payment systems, ...) and is fairly straight forward to implement - I don't see big upsides to having that here.

**Comment by mitar** [comment]
I mean, it is still duplicated code one has to locally maintain. I think having the basic claims being populated, with one being able to add more claims before writing it out, would be nice. Like all other handlers are. Especially if various strategies can contribute to the output of the handler, then one can even decouple which claims come from where.
