### ISSUE TITLE
ResourceOwnerPasswordCredentialsGrantHandler returns 500 error if password in token request is incorrect

### ISSUE THREAD

**Issue by vineet-garg** [ory/fosite#582]
**Describe the bug**

500 error returned if wrong password specified in a token request. 
The handler is configured to use memory store.

**To Reproduce**

1. configure memory store
2. invoke 
ResourceOwnerPasswordCredentialsGrantHandler HandleTokenEndpointRequest method with wrong password in the request.
3. the error returned is 500 server error

use 

**Expected behavior**

4XX error should be returned as it is an issue with user input. 

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

The error handling in both the files : flow_resource_owner.go 
if username == "" || password == "" {
		return errorsx.WithStack(fosite.ErrInvalidRequest.WithHint("Username or password are missing from the POST body."))
	} else if err := c.ResourceOwnerPasswordCredentialsGrantStorage.Authenticate(ctx, username, password); errors.Is(err, fosite.ErrNotFound) {
		return errorsx.WithStack(fosite.ErrInvalidGrant.WithHint("Unable to authenticate the provided username and password credentials.").WithWrap(err).WithDebug(err.Error()))
	} else if err != nil {
		return errorsx.WithStack(fosite.ErrServerError.WithWrap(err).WithDebug(err.Error()))
	}

and memory.go 
func (s *MemoryStore) Authenticate(_ context.Context, name string, secret string) error {
	s.usersMutex.RLock()
	defer s.usersMutex.RUnlock()

	rel, ok := s.Users[name]
	if !ok {
		return fosite.ErrNotFound
	}
	if rel.Password != secret {
		return errors.New("Invalid credentials")
	}
	return nil
}

are not aligned and seems to be contributing to the issue.

**Comment by aeneasr** [comment]
We welcome contributions!

**Comment by vineet-garg** [comment]
I can fix this. The desired error code in this case is 400 invalid_grant ?

**Comment by aeneasr** [comment]
I think that would be acceptable
