### ISSUE TITLE
Failed to upgrade to v0.40.0

### ISSUE THREAD

**Issue by mitar** [ory/fosite#597]
**Describe the bug**

I cannot upgrade to fosite v0.40.0.

**To Reproduce**

I have `go.mod` with:

```
github.com/ory/fosite v0.39.0
github.com/ory/x v0.0.215
```

I run:

```
go get -u github.com/ory/fosite@v0.40.0
```

I get:

```
go get: github.com/ory/x@v0.0.212 updating to
	github.com/ory/x@v0.0.239 requires
	github.com/ory/cli@v0.0.49 requires
	github.com/ory/kratos@v0.5.5-alpha.1.0.20210319103511-3726ed4d145a requires
	github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Expected behavior**

`fosite` updates.

**Environment**

Linux Ubuntu 16.04, go1.16.4.

**Additional context**

I am mostly opening this to see if this is "only me" situation or if somebody else has the same problem.

**Comment by mitar** [comment]
Manually updating `go.mod` worked.

**Comment by aeneasr** [comment]
„go get -u“ updates all the dependency’s versions and is a relict of pre-go modules and should generally be avoided!
