### ISSUE TITLE
Encrypted JWTs for both id_tokens and client assertions

### ISSUE THREAD

**Issue by vivshankar** [ory/fosite#631]
**Is your feature request related to a problem? Please describe.**

ID tokens and client assertions (both for JWT bearer grant flow and for private_key_jwt authentication) are generally signed and optionally encrypted. In general, an encrypted token requirement comes up in industries like government or finance.

**Describe the solution you'd like**

The request is to add this capability by default in Fosite with an extension, effectively, to the JWTStrategy.

**Describe alternatives you've considered**

1. Add a handler in the provider after the id_token is generated that encrypts as configured on the client/provider config.
2. Implement a client_authentication strategy that also caters for encrypted JWTs

**Additional context**

N/A

**Comment by vivshankar** [comment]
@aeneasr For the ID token etc., this is relatively easy to accomplish with a custom implementation of JWTStrategy and performing the encryption on the Generate function. Perhaps a couple of client properties should be made available such as the algorithms to be used. I would just match it to the client_metadata properties in the DCR spec.

However, for inbound (client_assertion, request_object etc.), a new `Decrypt` function would be necessary in the JWTStrategy or a new `EncryptedJWTStrategy`. Again, the client properties should ideally match the DCR spec.

This should be a relatively simple extension with a simple example. Please let me know if this makes sense.

**Comment by aeneasr** [comment]
Sorry for the late reply, that sounds like a good approach!

**Comment by vivshankar** [comment]
@aeneasr This is a regarding a change I see in the master branch.

```
type Signer interface {
	Generate(ctx context.Context, claims MapClaims, header Mapper) (string, string, error)
	Validate(ctx context.Context, token string) (string, error)
	Hash(ctx context.Context, in []byte) ([]byte, error)
	Decode(ctx context.Context, token string) (*Token, error)
	GetSignature(ctx context.Context, token string) (string, error)
	GetSigningMethodLength(ctx context.Context) int
}
```

It looks like it is just a name change from `JWTStrategy` to `Signer`. I am curious about the thought process behind this and changes that might have been proposed/are being made.

**Comment by aeneasr** [comment]
Primarily because it is only used to sign tokens currently, but we can also name it something else
