### ISSUE TITLE
Rollback is not called if there is a panic

### ISSUE THREAD

**Issue by mitar** [ory/fosite#637]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Current use of `BeginTx`, `CommitTx` and `RollbackTx` in Fosite is problematic because it does not call `RollbackTx` when panic happens. We could assume that Fosite itself does not panic, but that is not necessary true for code it calls into. For example, I had a bug inside my storage implementation which triggered panic. As the panic propagated and was handled higher up in my request handler and logged, transaction itself was not rolled back, leaving the connection over it in an inconsistent state. With connection pooling that brought some stability issues.

### Reproducing the bug

Sadly I do not have a simple reproduction here. One which I was able to do is with Sqlite and setting `SetMaxOpenConns` to 1. Then if a transaction is not rolled back, no other operation can be done on the database and my code hangs. This is how I am now testing that all transactions are properly rolled back.

### Version

observed on current master branch

**Comment by aeneasr** [comment]
This is also the case for `os.Exit`, `*.Fatal*` and other exit scenarios such as unhandled SIGHUP. Most of these we can't detect. IMO catching panics isn't solvable without a substantial transaction refactor. Keep in mind that fosite has transactions optionally available, some storage engines don't even support transactions! The question is if that's worth the effort, as panics are rare and retries are cheap ("oh the server crashed, guess I need to try and refresh the token again").

**Comment by mitar** [comment]
I do not think perfect (catching all possible ways code can exist) should be the enemy of good: catching a standard way for Go code to throw an exception when there is a bug in the code it is calling into, and cleaning up. In fact, Go gives you a nice way to cleanup. I would even say that it would simplify existing code.

See [here](https://github.com/ory/fosite/blob/0a48821b156f4a5dffa0f7149d30d5cf02636f37/handler/oauth2/flow_authorize_code_token.go#L174-L191). There is so many `storage.MaybeRollbackTx` cases in there. All that could be moved into one `defer` and this is it.

I can try to do a MR if it would be an acceptable change.
