### ISSUE TITLE
How to verify assess_token , I don't see any documentation on this

### ISSUE THREAD

**Issue by JeffreyBool** [ory/fosite#639]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Cómo verificar assess_token , no veo ninguna documentación al respecto

### Reproducing the bug

Cómo verificar assess_token , no veo ninguna documentación al respecto

### Version

1

**Comment by aeneasr** [comment]
Hey, unfortunately we do not speak any other language than English and German in the team at the moment. Could you please ask your question in English? Thank you!

**Comment by JeffreyBool** [comment]
> 嘿，不幸的是，我们目前团队中除了英语和德语之外不会说任何其他语言。你能用英语问你的问题吗？谢谢！

How to verify assess_token , I don't see any documentation on this

**Comment by mitar** [comment]
You can do something like:

```
tokenType, ar, err := provider.IntrospectToken(ctx, fosite.AccessTokenFromRequest(req), fosite.AccessToken, session)
... check error
if tokenType != fosite.AccessToken {
   ... error
}
... all good, access token valid
```

**Comment by JeffreyBool** [comment]
> You can do something like:
> 
> ```
> tokenType, ar, err := provider.IntrospectToken(ctx, fosite.AccessTokenFromRequest(req), fosite.AccessToken, session)
> ... check error
> if tokenType != fosite.AccessToken {
>    ... error
> }
> ... all good, access token valid
> ```

Thanks, is there an actual open source project reference? The official project is too complicated
