### ISSUE TITLE
Avoid indirect dependency on `github.com/oleiade/reflections@v1.0.0` to avoid breaking Dependabot for projects that use fosite

### ISSUE THREAD

**Issue by cfryanr** [ory/fosite#640]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

A recent PR updated fosite's direct dependency on `github.com/oleiade/reflections@v1.0.0` to v1.0.1 (#587). This was to avoid the problem described in https://github.com/oleiade/reflections/issues/14 where the developer of that project changed the checksum of v1.0.0.

Unfortunately, the latest version of fosite still carries indirect dependencies on `github.com/oleiade/reflections@v1.0.0`. This can be seen by starting a new Go project which contains only a `go.mod` file with the following contents and then running `go mod graph | grep 'github.com/oleiade/reflections@v1.0.0'`.

```go
module fositedeps

go 1.17

require (
	github.com/ory/fosite v0.41.0
)
```

Following the dependency graph from the `go mod graph` output indicates that the latest version of fosite indirectly depends on a very old version of fosite (v0.29.0) which directly depends on the broken reflections v1.0.0.

This indirect dependency is not a problem in terms of being able to compile and run a project which imports the latest fosite. The impact is felt when that project starts to use dependency scanning software like GitHub's Dependabot, which analyzes the project's `go.sum` file, gets an error about reflections v1.0.0's checksum, and then refuses to continue, effectively disabling Dependabot for the project. Dependabot will stop flagging project dependencies that have updates available or have known security vulnerabilities.

### Describe your ideal solution

Ideally the simple test project described above would not have `github.com/oleiade/reflections@v1.0.0` anywhere in its dependency graph, and would use v1.0.1 instead. Running `go mod tidy` for that project would not put reflections v1.0.0 anywhere in the `go.sum` file.

I think the dependency exists because old versions of ory/x directly depended on the old version of fosite. Newer versions of ory/x don't have that dependency. If all indirect dependencies on ory/x were updated to use newer versions of ory/x, then the indirect dependency on reflections v1.0.0 should go away.

### Workarounds or alternatives

Our project added a `replace` directive to work around the problem. See https://github.com/vmware-tanzu/pinniped/blob/adf04d29f77fe54fa7bc3c7f9cf11f258303c13a/go.mod#L5-L18.

However, adding a replace directive is less than ideal because then any project which depends on our project would also need to know to add the same replace directive to avoid having a similar problem. It would be better if the replace directive were not needed.

### Version

v0.41.0

### Additional Context

Thanks for providing this great open source library!

**Comment by aeneasr** [comment]
Sorry! I missed the notification! Absolutely, please feel free to add a PR :)
