### ISSUE TITLE
Support OAuth 2.0 Demonstrating Proof-of-Possession at the Application Layer

### ISSUE THREAD

**Issue by kokukuma** [ory/fosite#641]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We're using fosite in our application. And Some of our clients have to use a lot of feature we provides, it means that we have to provide high privileged Access Token. In this situation, I think sender-constrained token is useful.

OAuth 2.0 Demonstrating Proof-of-Possession at the Application Layer(dpop) is still draft, 
but I think it is useful especially for a public client that have to get high privileged Access Token.
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-04

Currently, we implemented the feature in our application outside of fosite.
Just, the token endpoint gets DPoP Proof JWT and verify it, and save a JWK SHA-256 Thumbprint with Access Token.
When a client access to resource server, the resource server can get token information from introspection endpoint and verify the thumbprint is same between the token information and a DPoP Proof JWT that is passed with Access Token.

### Describe your ideal solution

Supprt this feature on fosite is very useful.
My expectation of what the fosite should do is like below,
+ Add a method on AccessRequest to obtaine DPoP Proof JWT and JWK Thumbprint.
+ Add DPoP handler to verify DPoP Proof JWT on HandleTokenEndpointRequest method.
+ Change the token_type based on the existance of JWK Thumbprint on AccessRequest.
+ Add cnf/jkt on token introspection response.

If this idea is match with your perspective, I'd like to create a PR.

### Workarounds or alternatives

Continue to implement the feature outside of fosite.

### Version

v0.40.2

**Comment by aeneasr** [comment]
Thank you so much for this proposal! I think sender constraint access tokens are very interesting indeed. For Fosite unfortunately we have a policy that only finalized RFCs can be added. Reason being that RFCs in draft are often changed, use unclear (and thus hard to implement correctly) language, or are abandoned.

Once the RFC is out of draft it would be a great addition!

**Comment by kokukuma** [comment]
Thank you for your rely!

> For Fosite unfortunately we have a policy that only finalized RFCs can be added. Reason being that RFCs in draft are often changed, use unclear (and thus hard to implement correctly) language, or are abandoned.

I see, I understood. 
I'm looking forward it to be RFC!
