### ISSUE TITLE
Fragment is not escaped properly when computing the authorize response redirect URL

### ISSUE THREAD

**Issue by ste93cry** [ory/fosite#648]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When writing the authorize response, different response modes are supported: form post, query and fragment. For the fragment mode, the URL values are joined together using `&` as separator between each pair of key/value and `=` for separator between the key and value. Although the [RFC3896](https://datatracker.ietf.org/doc/html/rfc3986) does not mandate to escape those characters in the fragment, it makes sense to do it because otherwise every value containing them will break the whole fragment. Before #509, the fragment was encoded and then appended plain to the final URL to avoid double-escaping issues. However, in that PR, a regression was introduced in `URLSetFragment` that makes the values of the fragment not be escaped. When `String()` is called subsequently on the `net.URL` object, Go strictly follows the aforementioned RFC and does not escape the fragment, leading to the issue.

### Reproducing the bug

```sh
$ git clone https://github.com/ory/fosite-example
$ go run main.go
$ curl -X POST --data-raw 'scopes=openid&scopes=offline&username=peter' -i 'http://localhost:3846/oauth2/auth?client_id=my-client&redirect_uri=http%3A%2F%2Flocalhost%3A3846%2Fcallback&response_type=id_token%20code&scope=photos+openid+offline&state=%7B%22foo%22%3A%22bar%3Dbaz%26baz%3Dfoo%22%7D&nonce=some-random-nonce&code_challenge=KcstGto0NlamBHCw_hEABNx5hiFaUX5qDhEYos8Mk0M&code_challenge_method=S256'
```

If you take a look at the `Location` header returned in the response, you will see that it contains a fragment with the `state` parameter which is not properly escaped

### Version

0.42.0

### Additional Context

This bug is actually affecting Hydra starting from version `1.9` and changes how the fragment was escaped up to version `1.8.5`

**Comment by aeneasr** [comment]
Thank you! Fixes (with tests) would be highly appreciated :)

**Comment by ste93cry** [comment]
I would love to contribute, but I'm not sure how we should solve this issue in practice: the `URLSetFragment` function mutates the input `net.URL` object directly, while we should compute the fragment string separately instead and then append it to the URL. While it is indeed possible to change the function signature to make it return a `string`, this would be a BC break. How do you suggest me to proceed?
