### ISSUE TITLE
Support 'Web Message' Response Ty;e

### ISSUE THREAD

**Issue by matty234** [ory/fosite#657]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The web message response type is used by commercial OAuth2 services (such as Auth0) to support token retrieval without requiring the browsing context to change.

### Describe your ideal solution

The ideal solution would be for HTML containing the WebMessage script (with a specific origin matching the redirect URL) to be returned when the `response_type` is set to `web_message`.

The approach could be restricted to only public clients using PKCE to prevent misuse?

### Workarounds or alternatives

-

### Version

v0.42.1

**Comment by aeneasr** [comment]
Please see https://github.com/ory/fosite/pull/658#pullrequestreview-920649559
