### ISSUE TITLE
MTLS client authentication and certificate bound access tokens

### ISSUE THREAD

**Issue by vivshankar** [ory/fosite#661]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Context and scope

The context of this implementation is covered by the [RFC](https://datatracker.ietf.org/doc/html/rfc8705). The proposal is to support `tls_client_auth` (but not `self_signed_tls_client_auth`) and certificate based token binding.

### Goals and non-goals

**Goals**

- Prescriptive mechanism that requires the client certificate authentication to be completed at a proxy layer and to propagate the certificate as a header to the Fosite implementation.
- Certificate bound access tokens supported across all client authentication types

**Non goals**

- Will not support `self_signed_tls_client_auth`
- Will not provide a server that performs MTLS handshake. Requires a proxy to perform the mutual TLS handshake.

### The design

The proposal is to add the following:

1. Config property for the client certificate request header name
2. `CertBoundTokenSession` that exposes functions such as `GetCertificate` and `SetConformationClaim`
3. `CertBoundTokenHandler` that generates the thumbprint and implements the token handler interface
4. `TLSAuthenticatedClient` interface that extends the `Client` interface to add functions that indicate the certificate attribute to be compared and whether certificate binding is enabled.
5. Update the DefaultClientAuthenticationStrategy to validate the existence of the certificate based on the availability of `TLSAuthenticatedClient`.

### APIs

N/A. This is an update to Fosite.

### Data storage

No new storage interface required.

**Comment by vivshankar** [comment]
@aeneasr I have an implementation for this that I can contribute. Please let me know if there's interest.

**Comment by mitar** [comment]
I think until RFC becomes a standard and not just proposed standard, this will not be accepted.

**Comment by vivshankar** [comment]
It isn't draft. It's been the only full RFC for sender constrained access tokens. You might be thinking about DPoP.

@mitar

**Comment by mitar** [comment]
Oh, sorry. I misread. Ignore my comment.

**Comment by aeneasr** [comment]
Just fyi, currently on vacation and not able to review this most likely in the next 2-3 weeks!

**Comment by aeneasr** [comment]
If we implement `tls_client_auth` I think it would be straight forward to also add `self_signed_tls_client_auth`. Or is there a reason why that would be a non-goal?

Regarding the mTLS handshake, would that not be trivial to implement using Go's HTTPS infrastructure? Or are there specifics required to deal with mTLS?

**Comment by aeneasr** [comment]
I see, that makes a lot of sense. Is the header where the certificate is included somehow standardized across these providers?

Regarding `self_signed_tls_client_auth`, I think it makes sense for third-party OAuth2 clients that wish to use mTLS but do not have the ability to either (a) purchase a certificate from e.g DigiCert or (b) do not have the ability to register a CA with the provider. It would also support use cases that want to leverage mTLS without needing to implement a full PKI infrastructure - this would be similar to the JWT client authentication but using mTLS instead. We could make this optional though, of course, if you are working in a regulated environment that mandates a well-known CA to have issued the certs. WDYT?

**Comment by vivshankar** [comment]
@aeneasr You really need to learn how to take vacation 😁 

The header approach is very common. Akamai, for example, offers the ability to include the full PEM and/or parsed PEM attributes. Most proxies offer this, nginx included. I suggest if Oathkeeper (the ory proxy? Cool names BTW) doesn't, you might consider enhancing it to make this available for people who want to use a pure ory solution with DNS resolution leading direct to Oathkeeper. In my own implementation, we use Akamai as the SSL termination point and it does the job of sending down the PEM post-mTLS handshake.

I can see the value of `self_signed_tls_client_auth` for test environments but I don't see this adding a lot of value once DPoP becomes a RFC implementation. In any case, we can pull it into the scope. I just don't have a ready implementation for this. Anyway, it just needs an additional jwks validation. Does it make sense, in this case, to configure the TLSAuthenticatedClient with another property that indicates the kid in the jwks? This would avoid needing to loop the entire jwks looking for a match.

**Comment by aeneasr** [comment]
> Edit: Your question regarding a standard cert header name... there isn't one, which is why I am proposing this as a new property we add to compose.Config (ClientCertificateHeaderName or some such).

I see, that makes sense to me! Is the format at least standardized?

> I can see the value of self_signed_tls_client_auth for test environments but I don't see this adding a lot of value once DPoP becomes a RFC implementation. 

That makes sense to me, I think it will be useful for guides and examples that allow one to get off the ground quickly!

>  I suggest if Oathkeeper (the ory proxy? Cool names BTW) doesn't, you might consider enhancing it to make this available for people who want to use a pure ory solution with DNS resolution leading direct to Oathkeeper.

That's a good proposal, we'll include it in the scope of the Ory Oathkeeper refactoring :)

> @aeneasr You really need to learn how to take vacation

I know 😅

**Comment by vivshankar** [comment]
The certificate format is usually url-encoded pem but the proxy may also have the ability to send certificate attributes and computed values. Here's a snippet from Cloudflare:

> For companies that use the client certificate for identification, Cloudflare can also forward any field of the client certificate as a custom header.

I know Akamai can be configured to send the pem cert.

**Comment by aeneasr** [comment]
I see, in that case it probably makes sense to have an interface defined which can be implemented for different providers (Akamai, Cloudflare, ...) as it sounds like everyone is doing this a little differently? That way, we could probably do away with the custom header config and just rely on the provider? We can also implement a generic provider which is a bit configurable to cover common use cases?

**Comment by vivshankar** [comment]
OK that makes sense. Maybe a tailored session interface that provides functions to get pem or specific attributes or the computed fingerprint?

**Comment by aeneasr** [comment]
makes sense!

**Comment by vivshankar** [comment]
Yes, I need to get back to contributing here. Assuming this is still of interest, I will try to get this in place over the next couple weeks.
