### ISSUE TITLE
Configuration hot reloading

### ISSUE THREAD

**Issue by aeneasr** [ory/fosite#666]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Hot reloading of config is not possible.

### Describe your ideal solution

We want to support hot reloading for all of Ory Fosite's configuration values.

### Workarounds or alternatives

None

### Version

master

**Comment by james-d-elliott** [comment]
Nice work!

**Comment by aeneasr** [comment]
Thank you :)
