### ISSUE TITLE
'unsupported_response_mode' is not a documented error code per core specifications

### ISSUE THREAD

**Issue by vivshankar** [ory/fosite#674]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When a client is configured with specific response modes and the request contains an invalid/unsupported response mode, Fosite returns "unsupported_response_mode". This is flagged as a violation by the FAPI Advanced Final conformance suite.

It appears that this error code is not defined in both the OAuth 2.0 or Open ID Connect core specifications.

See for OAuth 2.0 - https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1
See for OIDC - https://openid.net/specs/openid-connect-core-1_0.html#AuthError

While personally I think the error code is more correct, given the impact to certification, I recommend we change this to "invalid_request".

### Reproducing the bug

1. Configure the OAuth 2.0 client with response_modes set to "form_post".
2. Perform an authorization request with response_mode=query
3. The error response is "unsupported_response_mode".

### Version

0.42.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by james-d-elliott** [comment]
Conversation from the maillist: https://lists.openid.net/pipermail/openid-specs-ab/Week-of-Mon-20140317/004680.html

Seems for whatever reason multiple OP's implemented this. But there's no clear specification so I agree.

**Comment by aeneasr** [comment]
@james-d-elliott what is your recommendation for htis issue?

**Comment by james-d-elliott** [comment]
Well considering ory tends to lean towards following the spec I'd probably lean towards what the author said. Without reading the relevant specs more closely I think the `error` parameter would most likely match the `invalid_request` value, with context given in the `error_description` parameter. 

I can see there being room to implement it similarly to how other OP's implement it; but maybe allowing the implementer to choose this.. just not sure how to go about that with my current familiarity with the library.

**Comment by vivshankar** [comment]
Yes, the error can be mapped by overriding WriteAuthorizeError. Just doesn't seem worthwhile to me. Also if there is an intention to certify Hydra for FAPI Advanced Final, this will have to be done

**Comment by james-d-elliott** [comment]
I was thinking the solution that is most backwards compatible (i.e. not breaking) is add a method to `fosite.RFC6749Error` which returns a `fosite.RFC6749Error` after filtering the `ErrorField` via a method which alters unspecified `error` values to specified ones.

Though looking at the RFC6749Error I think this should realistically be broken into multiple parts:

- Documenting the usages of each error in (specifically which specification they come from and if there are any specific endpoints which should not return specific errors potentially) https://github.com/ory/fosite/blob/master/errors.go
- Documenting the usages of RFC6749Error outside of this (if any)
- Deciding on an action (i.e. if the above solution makes sense or another approach makes sense)

**Comment by vivshankar** [comment]
It is possible the MessageCatalog can be enhanced to compute the `error` and not just the error description. That way an implementer can effectively map `unsupported_response_mode` to `invalid_request` with no impact to backward compatibility.

**Comment by vivshankar** [comment]
@aeneasr If there is no interest in this issue, I can go ahead and close it. It was a minor issue (IMO) anyway.

**Comment by aeneasr** [comment]
At least from my end this is not a priority on our roadmap :) I agree with your sentiment
