### ISSUE TITLE
Example in documentation mistake

### ISSUE THREAD

**Issue by MatteoGioioso** [ory/fosite#692]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

This is not a bug, it is just a minor issue in the documentation.
The following snippet:
```
var config = &fosite.Config{
	AccessTokenLifespan: time.Minute * 30,
	// ...
}
```

should be:

```
var config = &compose.Config{
	AccessTokenLifespan: time.Minute * 30,
	// ...
}
```

### Reproducing the bug

This line here: https://github.com/ory/fosite/blob/c0c0effa1d7f0318a9eb1b37f9aa414889cbd942/README.md?plain=1#L310

### Version

v0.42.2

**Comment by james-d-elliott** [comment]
Please see the docs for the version of the library you're using. For example for the version you've mentioned: https://github.com/ory/fosite/tree/v0.42.2
