### ISSUE TITLE
Failing to fetch a PKCE request session fails requests even when PKCE is not enforced

### ISSUE THREAD

**Issue by jgresty** [ory/fosite#743]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

`GetPKCERequestSession` is always called when the `OAuth2PKCEFactory` is enabled, however returning `NotFound` from this function will fail a request even if `EnforcePKCE` is set to `false`. 

This means that it is not possible to enable this factory with existing sessions that do not use PKCE without returning a stub from `GetPKCERequestSession` - a workaround that means a real NotFound error from a PKCE enabled session will be masked.

The problem line being: https://github.com/ory/fosite/blob/45a6785cc54fcbd9195b0de4b821bb5fed6a41be/handler/pkce/handler.go#L127

### Reproducing the bug

1. Implement an `authorization_code` flow without the `OAuth2PKCEFactory`
2. Have a client start an auth code flow
3. Enable the `OAuth2PKCEFactory`, returning `fosite.NotFound` if a session does not exist
4. Finish the auth code flow with the created client

I would expect the client to complete the flow successfully when it is not using PKCE, however just having the middleware enabled causes the flow to fail.

### Version

0.42.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

None

### Additional Context

We have been running a service implemented with fosite and want to rollout PKCE support but cannot do so without invalidating all existing sessions because of this.

**Comment by james-d-elliott** [comment]
I've definitely included this handler and am not using PKCE in integration. I'm not seeing this issue on 0.44.0, not entirely sure if it was already fixed or if there is another reason for this issue.

**Comment by jgresty** [comment]
The handler will create dummy sessions for new requests that do not request PKCE, these sessions have empty strings for their challenge and method. So this bug will only happen for requests that begin before the factory is added then continue once it has been added. I'm sure that is a very small window and very unlikely to actually happen in the real world. However it seems odd that PKCE sessions are created even when not requested.

**Comment by james-d-elliott** [comment]
Theoretical patch that should handle both the needless session creation and the actual issue:

```diff
Subject: [PATCH] fix: pkce session generated unnecessarily
---
Index: handler/pkce/handler.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/handler/pkce/handler.go b/handler/pkce/handler.go
--- a/handler/pkce/handler.go	(revision daf3b15f0433c207e40601065cb9c92c52a025f2)
+++ b/handler/pkce/handler.go	(date 1680832900065)
@@ -47,6 +47,11 @@
 		return err
 	}
 
+	// We don't need a session if it's not enforced and not provided.
+	if challenge == "" && method == "" {
+		return nil
+	}
+
 	code := resp.GetCode()
 	if len(code) == 0 {
 		return errorsx.WithStack(fosite.ErrServerError.WithDebug("The PKCE handler must be loaded after the authorize code handler."))
@@ -71,17 +76,7 @@
 		// error response with the "error" value set to "invalid_request".  The
 		// "error_description" or the response of "error_uri" SHOULD explain the
 		// nature of error, e.g., code challenge required.
-		if c.Config.GetEnforcePKCE(ctx) {
-			return errorsx.WithStack(fosite.ErrInvalidRequest.
-				WithHint("Clients must include a code_challenge when performing the authorize code flow, but it is missing.").
-				WithDebug("The server is configured in a way that enforces PKCE for clients."))
-		}
-		if c.Config.GetEnforcePKCEForPublicClients(ctx) && client.IsPublic() {
-			return errorsx.WithStack(fosite.ErrInvalidRequest.
-				WithHint("This client must include a code_challenge when performing the authorize code flow, but it is missing.").
-				WithDebug("The server is configured in a way that enforces PKCE for this client."))
-		}
-		return nil
+		return c.validateNoPKCE(ctx, client)
 	}
 
 	// If the server supporting PKCE does not support the requested
@@ -108,6 +103,20 @@
 	return nil
 }
 
+func (c *Handler) validateNoPKCE(ctx context.Context, client fosite.Client) error {
+	if c.Config.GetEnforcePKCE(ctx) {
+		return errorsx.WithStack(fosite.ErrInvalidRequest.
+			WithHint("Clients must include a code_challenge when performing the authorize code flow, but it is missing.").
+			WithDebug("The server is configured in a way that enforces PKCE for clients."))
+	}
+	if c.Config.GetEnforcePKCEForPublicClients(ctx) && client.IsPublic() {
+		return errorsx.WithStack(fosite.ErrInvalidRequest.
+			WithHint("This client must include a code_challenge when performing the authorize code flow, but it is missing.").
+			WithDebug("The server is configured in a way that enforces PKCE for this client."))
+	}
+	return nil
+}
+
 func (c *Handler) HandleTokenEndpointRequest(ctx context.Context, request fosite.AccessRequester) error {
 	if !c.CanHandleTokenEndpointRequest(ctx, request) {
 		return errorsx.WithStack(fosite.ErrUnknownRequest)
@@ -123,8 +132,12 @@
 
 	code := request.GetRequestForm().Get("code")
 	signature := c.AuthorizeCodeStrategy.AuthorizeCodeSignature(ctx, code)
-	authorizeRequest, err := c.Storage.GetPKCERequestSession(ctx, signature, request.GetSession())
+	pkceRequest, err := c.Storage.GetPKCERequestSession(ctx, signature, request.GetSession())
 	if errors.Is(err, fosite.ErrNotFound) {
+		if verifier == "" {
+			return c.validateNoPKCE(ctx, request.GetClient())
+		}
+
 		return errorsx.WithStack(fosite.ErrInvalidGrant.WithHint("Unable to find initial PKCE data tied to this request").WithWrap(err).WithDebug(err.Error()))
 	} else if err != nil {
 		return errorsx.WithStack(fosite.ErrServerError.WithWrap(err).WithDebug(err.Error()))
@@ -134,9 +147,9 @@
 		return errorsx.WithStack(fosite.ErrServerError.WithWrap(err).WithDebug(err.Error()))
 	}
 
-	challenge := authorizeRequest.GetRequestForm().Get("code_challenge")
-	method := authorizeRequest.GetRequestForm().Get("code_challenge_method")
-	client := authorizeRequest.GetClient()
+	challenge := pkceRequest.GetRequestForm().Get("code_challenge")
+	method := pkceRequest.GetRequestForm().Get("code_challenge_method")
+	client := pkceRequest.GetClient()
 	if err := c.validate(ctx, challenge, method, client); err != nil {
 		return err
 	}
Index: handler/pkce/handler_test.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/handler/pkce/handler_test.go b/handler/pkce/handler_test.go
--- a/handler/pkce/handler_test.go	(revision daf3b15f0433c207e40601065cb9c92c52a025f2)
+++ b/handler/pkce/handler_test.go	(date 1680832900282)
@@ -126,6 +126,7 @@
 			expectErr: fosite.ErrInvalidGrant,
 			client:    pc,
 			code:      "invalid-code-2",
+			verifier:  "foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoo",
 		},
 		{
 			d:      "passes because auth code flow but pkce is not forced and no challenge given",

```
