### ISSUE TITLE
authorize_helper.isLoopbackAddress has flaws

### ISSUE THREAD

**Issue by it9gamelog** [ory/fosite#750]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

isLoopbackAddress from https://github.com/ory/fosite/blame/45a6785cc54fcbd9195b0de4b821bb5fed6a41be/authorize_helper.go#L144 allows pattern that are not loopback address, because of the bug in the regex

String such as `127.0.0.11230`, `127x0x0x11230`, `[::1]1230` is expected to returns `false` from this function, instead of `true`

I am proposing a fix in the repro section below.

I don't think this is security critical though, there seems to be no way to construct a real internet routable domain from this and probably has no open redirect problem.

### Reproducing the bug

```
package main

import (
	"fmt"
	"regexp"
)

// isLoopbackAddress from https://github.com/ory/fosite/blame/45a6785cc54fcbd9195b0de4b821bb5fed6a41be/authorize_helper.go#L144
func isLoopbackAddress(address string) bool {
	match, _ := regexp.MatchString("^(127.0.0.1|\\[::1\\])(:?)(\\d*)$", address)
	return match
}

func isLoopbackAddressFixed(address string) bool {
	match, _ := regexp.MatchString("^(127\\.0\\.0\\.1|\\[::1\\])(:\\d*)?$", address)
	return match
}

func main() {
	fmt.Println(isLoopbackAddress("127.0.0.11230") == isLoopbackAddressFixed("127.0.0.11230")) // BUG, expects false!
	fmt.Println(isLoopbackAddress("127x0x0x11230") == isLoopbackAddressFixed("127x0x0x11230")) // BUG, expects false!
	fmt.Println(isLoopbackAddress("[::1]1230") == isLoopbackAddressFixed("[::1]1230"))         // BUG, expects false!

	fmt.Println(isLoopbackAddress("127.0.0.1") == isLoopbackAddressFixed("127.0.0.1"))
	fmt.Println(isLoopbackAddress("127.0.0.1:1230") == isLoopbackAddressFixed("127.0.0.1:1230"))
	fmt.Println(isLoopbackAddress("[::1]") == isLoopbackAddressFixed("[::1]"))
	fmt.Println(isLoopbackAddress("[::1]:1230") == isLoopbackAddressFixed("[::1]:1230"))
}
```

### Version

45a6785cc54fcbd9195b0de4b821bb5fed6a41be (Latest)

### On which operating system are you observing this issue?

Other

### In which environment are you deploying?

Other

**Comment by aeneasr** [comment]
Thank you for the report! PRs with test cases are welcomed :)
