### ISSUE TITLE
clientCredentialsFromRequest should not expect Basic Authorization terms being URL Escaped

### ISSUE THREAD

**Issue by it9gamelog** [ory/fosite#753]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Around https://github.com/ory/fosite/blob/master/client_authentication.go#L298

I expect `clientCredentialsFromRequest` not doing `QueryUnescape`.

# Rationale

1. Per https://datatracker.ietf.org/doc/html/rfc7617, it does not metion about escaping user and password part. In addition, it specifically mention that username with colon is invalid, which wouldn't be the case if it's escaped.
2. As tested in Chrome, password with `%` is just passed as is, without encoded to `%25`

# Impact

If the client key or client secret contains plaintext "%", it will failed with unable to unescape or never match (unless it's specifically escaped manually in RP configuration)

### Reproducing the bug

1. Create a client credential with `%`
2. Build a token endpoint, and use basic authorization to pass the client secret.
3. It will fails with `The client secret in the HTTP authorization header could not be decoded from 'application/x-www-form-urlencoded'.` or fail to authenticate due to secret mismatch

### Version

latest

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by james-d-elliott** [comment]
This does not look like it's accurate to me. This function seems to only be used when basic auth is missing; see [these lines](https://github.com/ory/fosite/blob/master/client_authentication.go#L296-L297). If the basic auth header is present then the function returns.

The section of the function you've mentioned is attempting to parse the POST data which MUST be escaped per standard HTTP POST Form semantics, specifically the client secret, not the client credentials grant. This is also indicated by the error.

**Comment by aeneasr** [comment]
The spec does indeed very clearly require url decoding for these two parameters:

> Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [[RFC2617](https://datatracker.ietf.org/doc/html/rfc2617)] to authenticate with
   the authorization server.  The client identifier is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   [Appendix B](https://datatracker.ietf.org/doc/html/rfc6749#appendix-B), and the encoded value is used as the username; the client
   password is encoded using the same algorithm and used as the
   password.  The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.
