### ISSUE TITLE
use mattn/go-sqlite3 v2.0.3+incompatible no the new version

### ISSUE THREAD

**Issue by wuxingzhong** [ory/fosite#768]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

some problems: 
<img width="557" alt="image" src="https://github.com/ory/fosite/assets/7947984/d65627fa-bfb2-4a7a-80f2-9a0689b7d306">

according

![image](https://github.com/ory/fosite/assets/7947984/c3edeb36-9c7b-4643-b54a-c50b4e6381cb)

[go-sqlite3](https://github.com/mattn/go-sqlite3)

### Reproducing the bug

nothing

### Version

v0.44.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by james-d-elliott** [comment]
Fosite doesn't include this dep in the [go.mod](https://github.com/ory/fosite/blob/master/go.mod). Use the correct version when downloading the dependency:

`go get github.com/mattn/go-sqlite3@v1.14.17`

Ory has no control over which version you download.

**Comment by james-d-elliott** [comment]
Can you please provide clear reproduction instructions? I can't replicate this with the following:


```
go get github.com/mattn/go-sqlite3@v1.14.17
go get github.com/ory/fosite@v0.44.0
go mod tidy
```

**Comment by james-d-elliott** [comment]
This is due to a gobuffalo dependency. Will look closely as to why.

This can be worked around with `go mod edit -replace="github.com/mattn/go-sqlite3=github.com/mattn/go-sqlite3@v1.14.17"`
