### ISSUE TITLE
Make prefix used in HMACSHAStrategy configurable

### ISSUE THREAD

**Issue by mitar** [ory/fosite#789]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I think this is primarily vanity, but `HMACSHAStrategy` used hard-coded `ory_` prefix and I would prefer to have it be something branded for my own project.

### Describe your ideal solution

I think just additional config option to configure the prefix would work well.

### Workarounds or alternatives

Copying the `HMACSHAStrategy` and changing that small string. I think this is done in [authelia](https://github.com/authelia/authelia/blob/master/internal/oidc/core_strategy_hmac.go).

### Version

latest master

**Comment by mitar** [comment]
I think this has been done with https://github.com/ory/fosite/pull/816.

**Comment by aeneasr** [comment]
I agree, while it's still not possible out of the box, it's now easier to do this with the copy strategy.
